### ISSUE TITLE
Create database from command line

### ISSUE THREAD

**Issue by ly2ly** [odoo/docker#111]
Hello,

I want to create database from command line with docker. I try these lines

$ docker run -d -e POSTGRES_USER=odoo -e POSTGRES_PASSWORD=odoo --name db postgres:9.5
$ docker run -p 8069:8069 --name odoo --link db:db -t odoo -- -d test

But I got these errors

2017-05-17 05:58:37,441 1 INFO ? odoo: Odoo version 10.0-20170207
2017-05-17 05:58:37,442 1 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf
2017-05-17 05:58:37,442 1 INFO ? odoo: addons paths: ['/var/lib/odoo/addons/10.0', u'/mnt/extra-addons', u'/usr/lib/python2.7/dist-packages/odoo/addons']
2017-05-17 05:58:37,442 1 INFO ? odoo: database: odoo@172.17.0.2:5432
2017-05-17 05:58:37,443 1 INFO ? odoo.sql_db: Connection to the database failed
Traceback (most recent call last):
  File "/usr/bin/odoo", line 9, in <module>
    odoo.cli.main()
  File "/usr/lib/python2.7/dist-packages/odoo/cli/command.py", line 64, in main
    o.run(args)
  File "/usr/lib/python2.7/dist-packages/odoo/cli/server.py", line 164, in run
    main(args)
  File "/usr/lib/python2.7/dist-packages/odoo/cli/server.py", line 138, in main
    odoo.service.db._create_empty_database(db_name)
  File "/usr/lib/python2.7/dist-packages/odoo/service/db.py", line 79, in _create_empty_database
    with closing(db.cursor()) as cr:
  File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 622, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 164, in __init__
    self._cnx = pool.borrow(dsn)
  File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 505, in _locked
    return fun(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 573, in borrow
    **connection_info)
  File "/usr/lib/python2.7/dist-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
psycopg2.OperationalError: could not connect to server: Connection refused

	Is the server running on host "172.17.0.2" and accepting
	TCP/IP connections on port 5432?

What is the problem, are there other solution to do this?

**Comment by thomas15v** [comment]
Hi sir. You have to add the following flags to odoo:
`--db_host db --db_password odoo`

**Comment by sanjigue** [comment]
@thomas15v thx men
