### ISSUE TITLE
Mounting problem with ECS

### ISSUE THREAD

**Issue by teu** [odoo/docker#119]
Hi,

trying to set up odoo on AWS ECS, using 10.0 image. 
First tried without mounted volumes and it worked. Now tried with mounted volumes and getting:

```
ERROR odoo werkzeug: Error on request:
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 177, in run_wsgi
execute(self.server.app)
File "/usr/lib/python2.7/dist-packages/werkzeug/serving.py", line 165, in execute
application_iter = app(environ, start_response)
File "/usr/lib/python2.7/dist-packages/odoo/service/server.py", line 246, in app
return self.app(e, s)
File "/usr/lib/python2.7/dist-packages/odoo/service/wsgi_server.py", line 184, in application
return application_unproxied(environ, start_response)
File "/usr/lib/python2.7/dist-packages/odoo/service/wsgi_server.py", line 170, in application_unproxied
result = handler(environ, start_response)
File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 1306, in __call__
return self.dispatch(environ, start_response)
File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 1280, in __call__
return self.app(environ, start_wrapped)
File "/usr/lib/python2.7/dist-packages/werkzeug/wsgi.py", line 588, in __call__
return self.app(environ, start_response)
File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 1471, in dispatch
result = ir_http._dispatch()
File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_http.py", line 199, in _dispatch
return cls._handle_exception(e)
File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
return request._handle_exception(exception)
File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 766, in _handle_exception
return super(HttpRequest, self)._handle_exception(exception)
File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
result = request.dispatch()
File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 825, in dispatch
r = self._call_function(**self.params)
File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function
return checked_call(self.db, *args, **kwargs)
File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 119, in wrapper
return f(dbname, *args, **kwargs)
File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 327, in checked_call
result.flatten()
File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 1257, in flatten
self.response.append(self.render())
File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 1250, in render
return env["ir.ui.view"].render_template(self.template, self.qcontext)
File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 1029, in render_template
return self.browse(self.get_view_id(template)).render(values, engine)
File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 936, in get_view_id
return self.env['ir.model.data'].xmlid_to_res_id(template, raise_if_not_found=True)
File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_model.py", line 1048, in xmlid_to_res_id
return self.xmlid_to_res_model_res_id(xmlid, raise_if_not_found)[1]
File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_model.py", line 1039, in xmlid_to_res_model_res_id
return self.xmlid_lookup(xmlid)[1:3]
File "<string>", line 2, in xmlid_lookup
File "/usr/lib/python2.7/dist-packages/odoo/tools/cache.py", line 87, in lookup
value = d[key] = self.method(*args, **kwargs)
File "/usr/lib/python2.7/dist-packages/odoo/addons/base/ir/ir_model.py", line 1028, in xmlid_lookup
raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: web.login
```

Any idea what can be wrong?

**Comment by nhal** [comment]
We've been finding similar problems sharing and persisting the volumes as local data. The main problem we're encountering has to do with the UID of the odoo user inside the container, which is the one in use. Since UIDs are shared between host and container you'd need an odoo user at the right UID (104 if I recall correctly, I'll try to check it later) on your host with permissions on the folders where you store your data.

The volumes you're mounting are named volumes or mapped directories from your host? We didn't have any trouble with named volumes, but when trying to persist our data on an EBS instance we weren't allowed to access it from inside the container, since the user odoo has no rights over the UID 1000 (ubuntu user in the default amazon EC2 instances). We tried extending the Dockerfile to use the root user but that didn't help regarding data persistance.

If anyone has been able to persist data in a non-named volume it'd be great to know how it was accomplished.
