### ISSUE TITLE
when i try to send Customer Invoices by mail show this error

### ISSUE THREAD

**Issue by esgindy** [odoo/docker#121]
the send mail is working good with Qut and sales order but in the invoice i show this error how can i fix it ??

Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 648, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 685, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/openerp/http.py", line 321, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/openerp/http.py", line 314, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/openerp/http.py", line 964, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/openerp/http.py", line 514, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 892, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/addons/web/controllers/main.py", line 880, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/addons/portal_sale/portal_sale.py", line 62, in action_invoice_sent
    action_dict = super(account_invoice, self).action_invoice_sent(cr, uid, ids, context=context)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 381, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/addons/account/models/account_invoice.py", line 396, in action_invoice_sent
    default_template_id=template.id,
AttributeError: 'NoneType' object has no attribute 'id'

**Comment by thomas15v** [comment]
Looks like a Odoo misconfiguration issue to me. Did you deleted mail templates by any change? Otherwise try upgrading the account module to resolve it.

Also this prob should be in https://github.com/odoo/odoo.

**Comment by esgindy** [comment]
i deleted the templates after i change in it and i duplicate the same templates but for portal and change the name after that it give me this error so which module i need to upgrading and if i do the upgrading are any data i will lost or what  thx for your answer

**Comment by thomas15v** [comment]
There is a reason why templates are only visible in development mode. Because some data is hardcoded in odoo. If you delete templates you lose those pointers and crashes will occur. You can see id's that the code uses in "External Identifiers" (note: not all of them are used in code). 

Data should not be lost when upgrading the account module, however there exists a slight change that odoo will send a mail to users. I know this happens with the sale module. So I would temporary disable outgoing email before upgrading the module.
