### ISSUE TITLE
New database create Error

### ISSUE THREAD

**Issue by yevheniidehtiar** [odoo/docker#131]
From Odoo container:

```
017-10-19 22:53:50,338 1 INFO demo11 odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 1 connections to 'dbname=demo11 user=odoo password=xxxx host=db port=5432 sslmode=prefer'
20.10.2017 01:53:502017-10-19 22:53:50,353 1 INFO demo11 werkzeug: 10.42.0.1 - - [19/Oct/2017 22:53:50] "POST /web/database/create HTTP/1.1" 200 -
20.10.2017 02:00:382017-10-19 23:00:38,005 1 INFO ? odoo.service.server: Initiating shutdown
20.10.2017 02:00:382017-10-19 23:00:38,007 1 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown.
20.10.2017 02:00:412017-10-19 23:00:41,874 1 INFO ? odoo: Odoo version 11.0-20171013
20.10.2017 02:00:412017-10-19 23:00:41,876 1 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf
20.10.2017 02:00:412017-10-19 23:00:41,876 1 INFO ? odoo: addons paths: ['/var/lib/odoo/addons/11.0', '/usr/lib/python3/dist-packages/odoo/addons']
20.10.2017 02:00:412017-10-19 23:00:41,876 1 INFO ? odoo: database: odoo@db:5432
20.10.2017 02:00:412017-10-19 23:00:41,893 1 INFO ? odoo.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069
20.10.2017 02:00:422017-10-19 23:00:42,010 1 INFO ? odoo.addons.base.ir.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf
20.10.2017 02:00:422017-10-19 23:00:42,127 1 WARNING ? odoo.addons.base.res.res_currency: The num2words python library is not installed, l10n_mx_edi features won't be fully available.
20.10.2017 02:00:492017-10-19 23:00:49,463 1 INFO ? odoo.http: HTTP Configuring static files
20.10.2017 02:00:492017-10-19 23:00:49,483 1 INFO demo11 odoo.modules.loading: loading 1 modules...
20.10.2017 02:00:492017-10-19 23:00:49,508 1 INFO demo11 odoo.modules.loading: 1 modules loaded in 0.02s, 0 queries
20.10.2017 02:00:492017-10-19 23:00:49,513 1 ERROR demo11 odoo.sql_db: bad query: b"SELECT * FROM ir_model WHERE state='manual'"
20.10.2017 02:00:49ERROR: relation "ir_model" does not exist
20.10.2017 02:00:49LINE 1: SELECT * FROM ir_model WHERE state='manual'
20.10.2017 02:00:49                      ^
20.10.2017 02:00:49
20.10.2017 02:00:492017-10-19 23:00:49,514 1 ERROR demo11 odoo.modules.registry: Failed to load registry
20.10.2017 02:00:49Traceback (most recent call last):
20.10.2017 02:00:49  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 59, in __new__
20.10.2017 02:00:49    return cls.registries[db_name]
20.10.2017 02:00:49  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
20.10.2017 02:00:49    return func(self, *args, **kwargs)
20.10.2017 02:00:49  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
20.10.2017 02:00:49    a = self.d[obj].me
20.10.2017 02:00:49KeyError: 'demo11'
20.10.2017 02:00:49
20.10.2017 02:00:49During handling of the above exception, another exception occurred:
20.10.2017 02:00:49
20.10.2017 02:00:49Traceback (most recent call last):
20.10.2017 02:00:49  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 84, in new
20.10.2017 02:00:49    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
20.10.2017 02:00:49  File "/usr/lib/python3/dist-packages/odoo/modules/loading.py", line 346, in load_modules
20.10.2017 02:00:49    registry.setup_models(cr)
20.10.2017 02:00:49  File "/usr/lib/python3/dist-packages/odoo/modules/registry.py", line 262, in setup_models
20.10.2017 02:00:49    env['ir.model']._add_manual_models()
20.10.2017 02:00:49  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_model.py", line 287, in _add_manual_models
20.10.2017 02:00:49    cr.execute('SELECT * FROM ir_model WHERE state=%s', ['manual'])
20.10.2017 02:00:49  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 155, in wrapper
20.10.2017 02:00:49    return f(self, *args, **kwargs)
20.10.2017 02:00:49  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 232, in execute
20.10.2017 02:00:49    res = self._obj.execute(query, params)
20.10.2017 02:00:49psycopg2.ProgrammingError: relation "ir_model" does not exist
20.10.2017 02:00:49LINE 1: SELECT * FROM ir_model WHERE state='manual'
20.10.2017 02:00:49                      ^
20.10.2017 02:00:49
20.10.2017 02:00:492017-10-19 23:00:49,518 1 INFO demo11 odoo.http: Generating nondb routing


```

From Postgres container:
```
20.10.2017 01:53:50ERROR:  relation "ir_model" does not exist at character 15
20.10.2017 01:53:50STATEMENT:  SELECT * FROM ir_model WHERE state='manual'
```

**Comment by voldedore** [comment]
I was experiencing the same issue.

Firstly, try to temporary remove any addons in your mount volume. Restart container and it should be able to create database.

After that, you may add add-ons volumes again and (again) restart container.

**Comment by slowfood64** [comment]
hello voldedore, i have this issue,.. i install odoo community in window and connected to my hosting provider postgresql but when i create a database and i get this issue but i dont have a clue in programming i am newbie trying to install odoo for the family business where i remove this addons in my mount volume? can you help me? my email is robertoreyes.lr@gmail.com can you send me an email?

**Comment by voldedore** [comment]
I am not sure you're posting in the right place or I might misunderstand your problem.

If you are in trouble of **how to remove any mount volume**, this is actually how:

In your docker-compose.yml, change this

    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons:cached

To this

    volumes:
      - odoo-web-data:/var/lib/odoo
      # - ./addons:/mnt/extra-addons

But the main cause of this issue is not the mount volume but the wrong info inside each addons (one of mine has very long summary and description)

----

And if you are not working with a docker (or docker-compose files) so this repo is not the right place for your issue... and sorry for that, I am not further than you in the Odoo sector.

**Comment by d-fence** [comment]
Not Docker related and not able to reproduce
