### ISSUE TITLE
Docker FileNotFoundError (python error)

### ISSUE THREAD

**Issue by xilmen** [odoo/docker#152]
Hi, i'm on docker.
Docker version:
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:24:28 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   19e2cf6
 Built:        Thu Dec  7 22:23:07 2017
 OS/Arch:      linux/amd64
 Experimental: false

i run commands:

docker run -d -e POSTGRES_USER=odoo -e POSTGRES_PASSWORD=odoo --name db postgres:9.4
docker run -p 8069:8069 --name odoo --link db:db -t odoo

and i have this error after install plugin:

2017-12-21 21:35:39,293 1 INFO sql odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/sql/86/86777d963a35ed0277612194656952186f98f752
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7fac9e305730>, 1, False, ('fr_FR',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 944, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7fac9cdc9748>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 100, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/sql/86/86777d963a35ed0277612194656952186f98f752'
2017-12-21 21:35:39,294 1 INFO sql odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/sql/bd/bd402be51199b5dbe8b8019aaa197ff08384cf31
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7fac9e305730>, 1, False, ('fr_FR',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 944, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7fac9cdc9748>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 100, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/sql/bd/bd402be51199b5dbe8b8019aaa197ff08384cf31'
2017-12-21 21:35:39,294 1 INFO sql odoo.addons.base.ir.ir_attachment: _read_file reading /var/lib/odoo/filestore/sql/9c/9c47efe86d2251992fa7a68a4e8a206f33e5949d
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.ui.menu', <function IrUiMenu.load_menus at 0x7fac9e305730>, 1, False, ('fr_FR',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 944, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7fac9cdc9748>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_attachment.py", line 100, in _file_read
    r = base64.b64encode(open(full_path,'rb').read())
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/filestore/sql/9c/9c47efe86d2251992fa7a68a4e8a206f33e5949d'

Ty ;)

**Comment by veivaa** [comment]
In your docker run statements you do not have volumes for persistent data across container recreation. Is it so that everything works until you recreate the container e.g. after installing a new module? If this is the case, the problem is in filestore persistence. After you have recreated your container you do not have the files stored in Odoo filestore directory available any more. 

You can find an example of Odoo in Docker container with persistent volumes in Unkkuri blog at https://unkkuri.com/blog/unkkuri-blog-1/post/install-odoo-version-11-in-docker-container-21. With this you can have your docker volumes persist your data separate from your Odoo container life-cycle.

**Comment by xilmen** [comment]
Ok ty :)
