### ISSUE TITLE
[10.0] docker odoo scaffold(Permission denied)

### ISSUE THREAD

**Issue by NullAction** [odoo/docker#159]
```
$ sudo docker run -t --rm odoo:10 odoo scaffold openacademy addons
[sudo] password for guiwang: 
Traceback (most recent call last):
  File "/usr/bin/odoo", line 9, in <module>
    odoo.cli.main()
  File "/usr/lib/python2.7/dist-packages/odoo/cli/command.py", line 64, in main
    o.run(args)
  File "/usr/lib/python2.7/dist-packages/odoo/cli/scaffold.py", line 37, in run
    directory(args.dest, create=True),
  File "/usr/lib/python2.7/dist-packages/odoo/cli/scaffold.py", line 73, in directory
    os.makedirs(expanded)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/addons'
```

**Comment by veivaa** [comment]
The container does not have, and should not have, permissions to create /addons directory. This way this is working as expected. In the container you can create a new module in /mnt/extra-addons directory. Running the command in the following form does not give error:
`docker run -t --rm odoo:10.0 odoo scaffold openacademy **/mnt/extra-addons**`

The command creates the scaffold in the container and removes the container after run. You have to add persistent volumes or volume binds to your container to be able to develop the new scaffolded module forward. Please see more information about persistent volumes from Unkkuri's blog at https://unkkuri.com/blog/unkkuri-blog-1/post/install-odoo-version-11-in-docker-container-21. 

With the setup from the blog you can scaffold a new module with docker exec -command like this:
`docker exec unkkuri-odoo odoo scaffold openacademy /mnt/extra-addons `

After this you have the scaffold in /mnt/extra-addons and you can copy content to/from with docker cp command. I hope this helps you forward with Odoo development in Docker!

**Comment by Garibaldy** [comment]
The same thing  if you want to do it with  docker-compose 

docker-compose exec YourOdooInstanceName odoo scaffold openacademy /mnt/extra-addons

**Comment by carlosjmeilan** [comment]
m3hari, funcion perfecto de esa manera.

**Comment by HANZO-70** [comment]
> The container does not have, and should not have, permissions to create /addons directory. This way this is working as expected. In the container you can create a new module in /mnt/extra-addons directory. Running the command in the following form does not give error:
> `docker run -t --rm odoo:10.0 odoo scaffold openacademy /mnt/extra-addons`
> 
> The command creates the scaffold in the container and removes the container after run. You have to add persistent volumes or volume binds to your container to be able to develop the new scaffolded module forward. Please see more information about persistent volumes from Unkkuri's blog at https://unkkuri.com/blog/unkkuri-blog-1/post/install-odoo-version-11-in-docker-container-21.
> 
> With the setup from the blog you can scaffold a new module with docker exec -command like this:
> `docker exec unkkuri-odoo odoo scaffold openacademy /mnt/extra-addons `
> 
> After this you have the scaffold in /mnt/extra-addons and you can copy content to/from with docker cp command. I hope this helps you forward with Odoo development in Docker!

Thanks
