### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'Workbook' @ xlwt.Workbook()

### ISSUE THREAD

**Issue by open7c** [odoo/docker#161]
Latest Odoo Docker Version.

This Message occurs at many places, i.e. Download Lists as XLS.

Error in Browser:
```
Uncaught SyntaxError: Unexpected token T in JSON at position 0
https://odoo.epoproject.com/web#view_type=pivot&model=report.project.task.user&menu_id=142&action=178:1
Zurückverfolgung
SyntaxError: Unexpected token T in JSON at position 0
    at JSON.parse (<anonymous>)
    at HTMLIFrameElement.<anonymous> (https://odoo.epoproject.com/web/content/1042-838b8f1/web.assets_common.js:3843:379)
    at HTMLIFrameElement.dispatch (https://odoo.epoproject.com/web/content/1042-838b8f1/web.assets_common.js:892:451)
    at HTMLIFrameElement.elemData.handle (https://odoo.epoproject.com/web/content/1042-838b8f1/web.assets_common.js:865:173)
```
Error in Docker Log:
```
2018-01-11 14:39:34,868 1 ERROR odoo2 werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 254, in app
    return self.app(e, s)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 166, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1298, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1272, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python3/dist-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1473, in dispatch
    result = ir_http._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
    return super(Http, cls)._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/web_editor/models/ir_http.py", line 21, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/http_routing/models/ir_http.py", line 397, in _dispatch
    result = super(IrHttp, cls)._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/utm/models/ir_http.py", line 20, in _dispatch
    response = super(IrHttp, cls)._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_http.py", line 212, in _dispatch
    return cls._handle_exception(e)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_http.py", line 182, in _handle_exception
    return request._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 761, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_http.py", line 208, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 820, in dispatch
    r = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/pivot.py", line 23, in export_xls
    workbook = xlwt.Workbook()
AttributeError: 'NoneType' object has no attribute 'Workbook'
```

T.i.A.

**Comment by adrian-wechner** [comment]
Same problem here. Installing through docker:
sudo docker run -d -e POSTGRES_USER=odoo -e POSTGRES_PASSWORD=odoo --name db postgres:9.4
sudo docker run -v /home/adrian/Odoo/addons:/mnt/extra-addons -p 8069:8069 --name odoo --link db:db -t odoo

Then I install few apps and try an export. And I always get the same message when trying to export to excel.

**Comment by adrian-wechner** [comment]
I think I figuered out the problem. the python3 package xlwt is not installed. 
By adding to the Dockerfile you fix it:

- RUN pip3 install num2words
+ RUN pip3 install num2words xlwt

**Comment by arvindhatkar1974** [comment]
I am getting similar type of error, but not able to figure out, please help me for this  
Exception in thread GET_NEXT_LTP:
Traceback (most recent call last):
  File "C:\Anaconda3\envs\APH\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Anaconda3\envs\APH\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\arvin\AppData\Local\Temp\ipykernel_13400\1064182697.py", line 397, in GET_NEXT_LTP
  File "C:\Anaconda3\envs\APH\lib\site-packages\xlwings\main.py", line 1997, in value
    conversion.write(data, self, self._options)
  File "C:\Anaconda3\envs\APH\lib\site-packages\xlwings\conversion\__init__.py", line 48, in write
    pipeline(ctx)
  File "C:\Anaconda3\envs\APH\lib\site-packages\xlwings\conversion\framework.py", line 66, in __call__
    stage(*args, **kwargs)
  File "C:\Anaconda3\envs\APH\lib\site-packages\xlwings\conversion\standard.py", line 72, in __call__
    ctx.range = ctx.range.resize(len(ctx.value), len(ctx.value[0]))
  File "C:\Anaconda3\envs\APH\lib\site-packages\xlwings\main.py", line 2245, in resize
    return Range(self(1, 1), self(row_size, column_size)).options(**self._options)
  File "C:\Anaconda3\envs\APH\lib\site-packages\xlwings\main.py", line 1431, in __init__
    if cell1.sheet != cell2.sheet:
  File "C:\Anaconda3\envs\APH\lib\site-packages\xlwings\main.py", line 1538, in sheet
    return Sheet(impl=self.impl.sheet)
  File "C:\Anaconda3\envs\APH\lib\site-packages\xlwings\_xlwindows.py", line 815, in sheet
    return Sheet(xl=self.coords[0])
  File "C:\Anaconda3\envs\APH\lib\site-packages\xlwings\_xlwindows.py", line 801, in coords
    self.xl.Worksheet,
AttributeError: 'NoneType' object has no attribute 'Worksheet'
