### ISSUE TITLE
Download xls -> Uncaught TypeError: Cannot read property 'root' of undefined

### ISSUE THREAD

**Issue by open7c** [odoo/docker#166]
Latest Release (that already includes the xlwt Patch): every time we click on the "Download xls" Button (i.e. Tasks) the following error occurs:

```
Uncaught TypeError: Cannot read property 'root' of undefined
https://odoo.example.com/web/content/1653-05bf78b/web.assets_backend.js:1661
Zurückverfolgung
TypeError: Cannot read property 'root' of undefined
    at Class._computeHeaders (https://odoo.example.com/web/content/1653-05bf78b/web.assets_backend.js:1661:124)
    at Class.exportData (https://odoo.example.com/web/content/1653-05bf78b/web.assets_backend.js:1650:164)
    at Class._downloadTable (https://odoo.example.com/web/content/1653-05bf78b/web.assets_backend.js:1689:564)
    at Class._onButtonClick (https://odoo.example.com/web/content/1653-05bf78b/web.assets_backend.js:1694:47)
    at HTMLDivElement.dispatch (https://odoo.example.com/web/content/1647-aadf65c/web.assets_common.js:892:451)
    at HTMLDivElement.elemData.handle (https://odoo.example.com/web/content/1647-aadf65c/web.assets_common.js:865:173)
```

The Docker Console gives no Error.

**Comment by d-fence** [comment]
Sorry for the late answer, I cannot reproduce
