### ISSUE TITLE
container setup error

### ISSUE THREAD

**Issue by icf20** [odoo/docker#169]
just making `$ docker run -p 8069:8069 --name odoo --link db:db -t odoo`

give the next error

```
ERROR ? odoo.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1445, in _dispatch_nodb
    func, arguments = self.nodb_routing_map.bind_to_environ(request.httprequest.environ).match()
  File "/usr/lib/python3/dist-packages/werkzeug/routing.py", line 1563, in match
    raise NotFound()
werkzeug.exceptions.NotFound: 404: Not Found
```

**Comment by d-fence** [comment]
I cannot reproduce
