### ISSUE TITLE
Intermittent error: Reassigning task causes Error: Odoo Server Error  Traceback (most recent call last)..

### ISSUE THREAD

**Issue by ghost** [odoo/docker#186]
Docker version 18.03.0-ce, build 0520e24
Odoo 11.0-20180122 (Community Edition)
Postgres 10.3 
This just started happening today.

I ran into an issue when creating a task and clicking on Edit instead of Save. After I making all of my edits then clicking on save I get the following error:
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 947, in __get__
    value = record.env.cache.get(record, self)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 960, in get
    value = self._data[field][record.id][key]
KeyError: <odoo.api.Environment object at 0x7fce5c5d4be0>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 930, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 922, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/hr_timesheet/models/project.py", line 65, in write
    result = super(Task, self).write(values)
  File "/usr/lib/python3/dist-packages/odoo/addons/project/models/project.py", line 664, in write
    result = super(Task, self).write(vals)
  File "/usr/lib/python3/dist-packages/odoo/addons/mail/models/mail_thread.py", line 277, in write
    result = super(MailThread, self).write(values)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3008, in write
    self._write(old_vals)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 3223, in _write
    self.recompute()
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4801, in recompute
    vals = {n: rec[n] for n in ns}
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4801, in <dictcomp>
    vals = {n: rec[n] for n in ns}
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4659, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 951, in __get__
    self.determine_value(record)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1038, in determine_value
    self.compute_value(recs)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1018, in compute_value
    self._compute_value(records)
  File "/usr/lib/python3/dist-packages/odoo/fields.py", line 1009, in _compute_value
    getattr(records, self.compute)()
  File "/usr/lib/python3/dist-packages/odoo/addons/project/models/project.py", line 485, in _compute_elapsed
    dt_create_date, dt_date_assign, False, compute_leaves=True)
  File "/usr/lib/python3/dist-packages/odoo/addons/resource/models/resource.py", line 510, in get_work_hours_count
    for intervals in self._iter_work_intervals(start_dt, end_dt, resource_id, compute_leaves=compute_leaves):
  File "/usr/lib/python3/dist-packages/odoo/addons/resource/models/resource.py", line 435, in _iter_work_intervals
    resource_id=resource_id)
  File "/usr/lib/python3/dist-packages/odoo/addons/resource/models/resource.py", line 351, in _get_day_work_intervals
    working_intervals = [att_interval for att_interval in self._iter_day_attendance_intervals(day_date, start_time, end_time)]
  File "/usr/lib/python3/dist-packages/odoo/addons/resource/models/resource.py", line 351, in <listcomp>
    working_intervals = [att_interval for att_interval in self._iter_day_attendance_intervals(day_date, start_time, end_time)]
  File "/usr/lib/python3/dist-packages/odoo/addons/resource/models/resource.py", line 320, in _iter_day_attendance_intervals
    for calendar_working_day in self._get_day_attendances(day_date, start_time, end_time):
  File "/usr/lib/python3/dist-packages/odoo/addons/resource/models/resource.py", line 238, in _get_day_attendances
    if start_time and float_to_time(attendance.hour_to) < start_time:
  File "/usr/lib/python3/dist-packages/odoo/addons/resource/models/resource.py", line 21, in float_to_time
    return datetime.time(int(math.modf(float_hour)[1]), int(60 * math.modf(float_hour)[0]), 0)
ValueError: hour must be in 0..23

I was able to narrorow down the cause to reasigning the task to a co-worker.

Now I am receiving this error everytime I try to reasign a task. 

Agian this just started happening today.

The only thing I have done involving this odoo container after I spoun it up is run the following backup command every evening (I do this as the odoo database manager fails with a 500 error bug report coming soon).

docker exec -t <containerId> pg_dumpall -c -U postgres > dump_odooProd`date +%d-%m-%Y"_"%H_%M_%S`.sql
 
Tried to resolve this by:
-Logging out back in.
-Restarting the Posgresql container then the Odoo container.
-Clearing my browser cache.
We are pretty much dead in the water with this issue. :frowning_face: 
Any help and or insight into why this error is popping up would be amazing!

**Comment by land0** [comment]
I was just informed that our project manager created a group with various permissions and am sifting through what was done one can hope it is as simple as a permissions error.

**Comment by land0** [comment]
Well, restarting the odoo server after this error pops-up enables the employee to create a new task and assign it. The original task fails with the same error if you try to reasign it sfter the server is restarted.

**Comment by land0** [comment]
I readjusted the hard and soft memory limits according to the following formulas:
limit-memory-hard = 768 * your workers (eg 5) *1024 * 1024 = 3221225472
limit-memory-hard = 640 * your workers (e.g 5) *1024 * 1024 = 2684354560
I set workers according to the following formula:
(numberOfCPUs) * 2 + 1 
No more errors.

**Comment by d-fence** [comment]
Soved
