### ISSUE TITLE
ERROR: current transaction is aborted, commands ignored until end of transaction block

### ISSUE THREAD

**Issue by open7c** [odoo/docker#217]
Since today Odoo isn't working anymore after 1 year. How can we get this to work again?

```
2018-10-08 07:49:32,232 1 INFO ? odoo.http: HTTP Configuring static files 
2018-10-08 07:49:32,405 1 INFO open7 odoo.modules.loading: loading 1 modules... 
2018-10-08 07:49:32,415 1 INFO open7 odoo.modules.loading: 1 modules loaded in 0.01s, 0 queries 
2018-10-08 07:49:32,461 1 WARNING open7 odoo.modules.graph: module auth_crypt: not installable, skipped 
2018-10-08 07:49:32,570 1 WARNING open7 odoo.modules.graph: module professional_templates: not installable, skipped 
2018-10-08 07:49:32,647 1 WARNING open7 odoo.modules.graph: module plugin-customstyle: not installable, skipped 
2018-10-08 07:49:32,736 1 WARNING open7 odoo.modules.graph: module plugin-timesheet_report: not installable, skipped 
2018-10-08 07:49:32,743 1 WARNING open7 odoo.modules.graph: module base_vat_autocomplete: not installable, skipped 
2018-10-08 07:49:32,777 1 WARNING open7 odoo.modules.graph: module account_invoicing: not installable, skipped 
2018-10-08 07:49:32,804 1 WARNING open7 odoo.modules.graph: module web_planner: not installable, skipped 
2018-10-08 07:49:32,841 1 ERROR open7 odoo.modules.graph: module payment: Unmet dependencies: account 
2018-10-08 07:49:32,842 1 ERROR open7 odoo.modules.graph: module sale_crm: Unmet dependencies: sale_management, crm 
2018-10-08 07:49:32,842 1 ERROR open7 odoo.modules.graph: module hr_timesheet: Unmet dependencies: analytic, project, uom 
2018-10-08 07:49:32,842 1 ERROR open7 odoo.modules.graph: module delivery: Unmet dependencies: sale_stock, sale_management 
2018-10-08 07:49:32,842 1 ERROR open7 odoo.modules.graph: module l10n_at: Unmet dependencies: account 
2018-10-08 07:49:32,842 1 ERROR open7 odoo.modules.graph: module purchase: Unmet dependencies: account 
2018-10-08 07:49:32,842 1 ERROR open7 odoo.modules.graph: module account: Unmet dependencies: product, analytic, digest 
2018-10-08 07:49:32,842 1 ERROR open7 odoo.modules.graph: module payment_transfer: Unmet dependencies: payment 
2018-10-08 07:49:32,842 1 ERROR open7 odoo.modules.graph: module crm: Unmet dependencies: digest 
2018-10-08 07:49:32,842 1 ERROR open7 odoo.modules.graph: module crm_phone_validation: Unmet dependencies: crm 
2018-10-08 07:49:32,842 1 ERROR open7 odoo.modules.graph: module sale: Unmet dependencies: payment 
2018-10-08 07:49:32,842 1 ERROR open7 odoo.modules.graph: module account_bank_statement_import: Unmet dependencies: account 
2018-10-08 07:49:32,842 1 ERROR open7 odoo.modules.graph: module base_vat: Unmet dependencies: account 
2018-10-08 07:49:32,842 1 ERROR open7 odoo.modules.graph: module project: Unmet dependencies: rating, digest 
2018-10-08 07:49:32,842 1 ERROR open7 odoo.modules.graph: module analytic: Unmet dependencies: uom 
2018-10-08 07:49:32,842 1 ERROR open7 odoo.modules.graph: module sale_management: Unmet dependencies: sale, digest 
2018-10-08 07:49:32,842 1 ERROR open7 odoo.modules.graph: module procurement_jit: Unmet dependencies: sale_stock 
2018-10-08 07:49:32,842 1 ERROR open7 odoo.modules.graph: module product: Unmet dependencies: uom 
2018-10-08 07:49:32,842 1 ERROR open7 odoo.modules.graph: module project_timesheet_holidays: Unmet dependencies: hr_timesheet 
2018-10-08 07:49:32,842 1 ERROR open7 odoo.modules.graph: module sale_timesheet: Unmet dependencies: sale_management, hr_timesheet 
2018-10-08 07:49:32,842 1 ERROR open7 odoo.modules.graph: module sale_stock: Unmet dependencies: sale, stock_account 
2018-10-08 07:49:32,842 1 ERROR open7 odoo.modules.graph: module stock: Unmet dependencies: product 
2018-10-08 07:49:32,843 1 ERROR open7 odoo.modules.graph: module stock_account: Unmet dependencies: stock, account 
2018-10-08 07:49:32,843 1 ERROR open7 odoo.modules.graph: module hr_recruitment: Unmet dependencies: digest 
2018-10-08 07:49:32,843 1 INFO open7 odoo.modules.loading: loading 30 modules... 
2018-10-08 07:49:34,231 1 INFO open7 odoo.modules.loading: 30 modules loaded in 1.39s, 0 queries 
2018-10-08 07:49:34,884 1 INFO open7 odoo.modules.loading: Modules loaded. 
2018-10-08 07:49:34,900 1 INFO open7 odoo.addons.base.models.ir_http: Generating routing map 
2018-10-08 07:49:35,078 1 WARNING open7 odoo.modules.module: module web_planner: module not found 
2018-10-08 07:49:35,078 1 WARNING open7 odoo.modules.module: module web_planner: module not found 
2018-10-08 07:49:35,081 1 ERROR open7 odoo.sql_db: bad query: b'SELECT "ir_attachment".id FROM "ir_attachment" WHERE (((("ir_attachment"."active" = true)  AND  "ir_attachment"."res_field" IS NULL )  AND  ("ir_attachment"."type" = \'binary\'))  AND  ("ir_attachment"."url" = \'/web/static/lib/bootstrap/js/affix.js\')) ORDER BY "ir_attachment"."id" DESC  limit 1'
ERROR: column ir_attachment.active does not exist
LINE 1: ..."ir_attachment".id FROM "ir_attachment" WHERE (((("ir_attach...
                                                             ^
 
2018-10-08 07:49:35,081 1 ERROR open7 odoo.sql_db: bad query: b'SELECT "ir_attachment".id FROM "ir_attachment" WHERE (((("ir_attachment"."active" = true)  AND  "ir_attachment"."res_field" IS NULL )  AND  ("ir_attachment"."type" = \'binary\'))  AND  ("ir_attachment"."url" = \'/web/static/lib/bootstrap/js/transition.js\')) ORDER BY "ir_attachment"."id" DESC  limit 1'
ERROR: current transaction is aborted, commands ignored until end of transaction block
 
2018-10-08 07:49:35,082 1 ERROR open7 odoo.sql_db: bad query: b'SELECT "ir_attachment".id FROM "ir_attachment" WHERE (((("ir_attachment"."active" = true)  AND  "ir_attachment"."res_field" IS NULL )  AND  ("ir_attachment"."type" = \'binary\'))  AND  ("ir_attachment"."url" = \'/web/static/lib/bootstrap-datetimepicker/src/js/bootstrap-datetimepicker.js\')) ORDER BY "ir_attachment"."id" DESC  limit 1'
ERROR: current transaction is aborted, commands ignored until end of transaction block
 
2018-10-08 07:49:35,082 1 WARNING open7 odoo.modules.module: module web_planner: module not found 
2018-10-08 07:49:35,083 1 ERROR open7 odoo.sql_db: bad query: b'SELECT "ir_attachment".id FROM "ir_attachment" WHERE (((("ir_attachment"."active" = true)  AND  "ir_attachment"."res_field" IS NULL )  AND  ("ir_attachment"."type" = \'binary\'))  AND  ("ir_attachment"."url" = \'/web_planner/static/src/js/web_planner_common.js\')) ORDER BY "ir_attachment"."id" DESC  limit 1'
ERROR: current transaction is aborted, commands ignored until end of transaction block
 
2018-10-08 07:49:35,084 1 ERROR open7 odoo.sql_db: bad query: b'SELECT "ir_attachment".id FROM "ir_attachment" WHERE (((("ir_attachment"."active" = true)  AND  "ir_attachment"."res_field" IS NULL )  AND  ("ir_attachment"."type" = \'binary\'))  AND  ("ir_attachment"."url" = \'/web/static/lib/bootstrap/less/variables.less\')) ORDER BY "ir_attachment"."id" DESC  limit 1'
ERROR: current transaction is aborted, commands ignored until end of transaction block
 
2018-10-08 07:49:35,084 1 ERROR open7 odoo.sql_db: bad query: b'SELECT "ir_attachment".id FROM "ir_attachment" WHERE (((("ir_attachment"."active" = true)  AND  "ir_attachment"."res_field" IS NULL )  AND  ("ir_attachment"."type" = \'binary\'))  AND  ("ir_attachment"."url" = \'/web/static/lib/bootstrap/less/mixins/vendor-prefixes.less\')) ORDER BY "ir_attachment"."id" DESC  limit 1'
ERROR: current transaction is aborted, commands ignored until end of transaction block
 
2018-10-08 07:49:35,085 1 ERROR open7 odoo.sql_db: bad query: b'SELECT "ir_attachment".id FROM "ir_attachment" WHERE (((("ir_attachment"."active" = true)  AND  "ir_attachment"."res_field" IS NULL )  AND  ("ir_attachment"."type" = \'binary\'))  AND  ("ir_attachment"."url" = \'/web/static/lib/bootstrap/less/mixins/buttons.less\')) ORDER BY "ir_attachment"."id" DESC  limit 1'
ERROR: current transaction is aborted, commands ignored until end of transaction block
 
2018-10-08 07:49:35,086 1 ERROR open7 odoo.sql_db: bad query: b'SELECT "ir_attachment".id FROM "ir_attachment" WHERE (((("ir_attachment"."active" = true)  AND  "ir_attachment"."res_field" IS NULL )  AND  ("ir_attachment"."type" = \'binary\'))  AND  ("ir_attachment"."url" = \'/web/static/lib/bootstrap/less/mixins/clearfix.less\')) ORDER BY "ir_attachment"."id" DESC  limit 1'
ERROR: current transaction is aborted, commands ignored until end of transaction block
 
2018-10-08 07:49:35,086 1 ERROR open7 odoo.sql_db: bad query: b'SELECT "ir_attachment".id FROM "ir_attachment" WHERE (((("ir_attachment"."active" = true)  AND  "ir_attachment"."res_field" IS NULL )  AND  ("ir_attachment"."type" = \'binary\'))  AND  ("ir_attachment"."url" = \'/web/static/lib/bootstrap/less/mixins/size.less\')) ORDER BY "ir_attachment"."id" DESC  limit 1'
ERROR: current transaction is aborted, commands ignored until end of transaction block
 
2018-10-08 07:49:35,087 1 ERROR open7 odoo.sql_db: bad query: b'SELECT "ir_attachment".id FROM "ir_attachment" WHERE (((("ir_attachment"."active" = true)  AND  "ir_attachment"."res_field" IS NULL )  AND  ("ir_attachment"."type" = \'binary\'))  AND  ("ir_attachment"."url" = \'/web/static/src/less/variables.less\')) ORDER BY "ir_attachment"."id" DESC  limit 1'
ERROR: current transaction is aborted, commands ignored until end of transaction block
 
2018-10-08 07:49:35,087 1 ERROR open7 odoo.sql_db: bad query: b'SELECT "ir_attachment".id FROM "ir_attachment" WHERE (((("ir_attachment"."active" = true)  AND  "ir_attachment"."res_field" IS NULL )  AND  ("ir_attachment"."type" = \'binary\'))  AND  ("ir_attachment"."url" = \'/web/static/src/less/utils.less\')) ORDER BY "ir_attachment"."id" DESC  limit 1'
ERROR: current transaction is aborted, commands ignored until end of transaction block
 
2018-10-08 07:49:35,088 1 ERROR open7 odoo.sql_db: bad query: b'SELECT "ir_attachment".id FROM "ir_attachment" WHERE (((("ir_attachment"."active" = true)  AND  "ir_attachment"."res_field" IS NULL )  AND  ("ir_attachment"."type" = \'binary\'))  AND  ("ir_attachment"."url" = \'/web_editor/static/src/less/web_editor.variables.less\')) ORDER BY "ir_attachment"."id" DESC  limit 1'
ERROR: current transaction is aborted, commands ignored until end of transaction block
 
2018-10-08 07:49:35,089 1 ERROR open7 odoo.sql_db: bad query: b'SELECT "ir_attachment".id FROM "ir_attachment" WHERE (((("ir_attachment"."active" = true)  AND  "ir_attachment"."res_field" IS NULL )  AND  ("ir_attachment"."type" = \'binary\'))  AND  ("ir_attachment"."url" = \'/web/static/lib/bootstrap-datetimepicker/src/less/_bootstrap-datetimepicker.less\')) ORDER BY "ir_attachment"."id" DESC  limit 1'
ERROR: current transaction is aborted, commands ignored until end of transaction block
 
2018-10-08 07:49:35,089 1 ERROR open7 odoo.sql_db: bad query: b'SELECT "ir_attachment".id FROM "ir_attachment" WHERE (((("ir_attachment"."active" = true)  AND  "ir_attachment"."res_field" IS NULL )  AND  ("ir_attachment"."type" = \'binary\'))  AND  ("ir_attachment"."url" = \'/web/static/src/less/fonts.less\')) ORDER BY "ir_attachment"."id" DESC  limit 1'
ERROR: current transaction is aborted, commands ignored until end of transaction block
 
2018-10-08 07:49:35,090 1 ERROR open7 odoo.sql_db: bad query: b'SELECT "ir_attachment".id FROM "ir_attachment" WHERE (((("ir_attachment"."active" = true)  AND  "ir_attachment"."res_field" IS NULL )  AND  ("ir_attachment"."type" = \'binary\'))  AND  ("ir_attachment"."url" = \'/web/static/src/less/navbar.less\')) ORDER BY "ir_attachment"."id" DESC  limit 1'
ERROR: current transaction is aborted, commands ignored until end of transaction block
 
2018-10-08 07:49:35,091 1 ERROR open7 odoo.sql_db: bad query: b'SELECT "ir_attachment".id FROM "ir_attachment" WHERE (((("ir_attachment"."active" = true)  AND  "ir_attachment"."res_field" IS NULL )  AND  ("ir_attachment"."type" = \'binary\'))  AND  ("ir_attachment"."url" = \'/web/static/src/less/mimetypes.less\')) ORDER BY "ir_attachment"."id" DESC  limit 1'
ERROR: current transaction is aborted, commands ignored until end of transaction block
 
2018-10-08 07:49:35,091 1 ERROR open7 odoo.sql_db: bad query: b'SELECT "ir_attachment".id FROM "ir_attachment" WHERE (((("ir_attachment"."active" = true)  AND  "ir_attachment"."res_field" IS NULL )  AND  ("ir_attachment"."type" = \'binary\'))  AND  ("ir_attachment"."url" = \'/web/static/src/less/modal.less\')) ORDER BY "ir_attachment"."id" DESC  limit 1'
ERROR: current transaction is aborted, commands ignored until end of transaction block
 
2018-10-08 07:49:35,092 1 ERROR open7 odoo.sql_db: bad query: b'SELECT "ir_attachment".id FROM "ir_attachment" WHERE (((("ir_attachment"."active" = true)  AND  "ir_attachment"."res_field" IS NULL )  AND  ("ir_attachment"."type" = \'binary\'))  AND  ("ir_attachment"."url" = \'/web/static/src/less/animation.less\')) ORDER BY "ir_attachment"."id" DESC  limit 1'
ERROR: current transaction is aborted, commands ignored until end of transaction block
 
2018-10-08 07:49:35,093 1 ERROR open7 odoo.sql_db: bad query: b'SELECT "ir_attachment".id FROM "ir_attachment" WHERE (((("ir_attachment"."active" = true)  AND  "ir_attachment"."res_field" IS NULL )  AND  ("ir_attachment"."type" = \'binary\'))  AND  ("ir_attachment"."url" = \'/web/static/src/less/rainbow.less\')) ORDER BY "ir_attachment"."id" DESC  limit 1'
ERROR: current transaction is aborted, commands ignored until end of transaction block
 
2018-10-08 07:49:35,093 1 ERROR open7 odoo.sql_db: bad query: b'SELECT "ir_attachment".id FROM "ir_attachment" WHERE (((("ir_attachment"."active" = true)  AND  "ir_attachment"."res_field" IS NULL )  AND  ("ir_attachment"."type" = \'binary\'))  AND  ("ir_attachment"."url" = \'/web/static/src/less/datepicker.less\')) ORDER BY "ir_attachment"."id" DESC  limit 1'
ERROR: current transaction is aborted, commands ignored until end of transaction block
 
2018-10-08 07:49:35,093 1 WARNING open7 odoo.modules.module: module web_planner: module not found 
2018-10-08 07:49:35,094 1 ERROR open7 odoo.sql_db: bad query: b'SELECT "ir_attachment".id FROM "ir_attachment" WHERE (((("ir_attachment"."active" = true)  AND  "ir_attachment"."res_field" IS NULL )  AND  ("ir_attachment"."type" = \'binary\'))  AND  ("ir_attachment"."url" = \'/web_planner/static/src/less/web_planner_common.less\')) ORDER BY "ir_attachment"."id" DESC  limit 1'
ERROR: current transaction is aborted, commands ignored until end of transaction block
 
2018-10-08 07:49:35,095 1 ERROR open7 odoo.sql_db: bad query: b'SELECT "ir_attachment".id FROM "ir_attachment" WHERE (((("ir_attachment"."active" = true)  AND  "ir_attachment"."res_field" IS NULL )  AND  ("ir_attachment"."type" = \'binary\'))  AND  ("ir_attachment"."url" = \'/web_tour/static/src/less/tip.less\')) ORDER BY "ir_attachment"."id" DESC  limit 1'
ERROR: current transaction is aborted, commands ignored until end of transaction block
 
2018-10-08 07:49:35,095 1 ERROR open7 odoo.sql_db: bad query: b'SELECT "ir_attachment".id FROM "ir_attachment" WHERE (((("ir_attachment"."active" = true)  AND  "ir_attachment"."res_field" IS NULL )  AND  ("ir_attachment"."type" = \'binary\'))  AND  ("ir_attachment"."url" = \'/web_tour/static/src/less/keyframes.less\')) ORDER BY "ir_attachment"."id" DESC  limit 1'
ERROR: current transaction is aborted, commands ignored until end of transaction block
 
2018-10-08 07:49:35,096 1 ERROR open7 odoo.sql_db: bad query: b'SELECT "ir_attachment".id FROM "ir_attachment" WHERE (((("ir_attachment"."active" = true)  AND  "ir_attachment"."res_field" IS NULL )  AND  ("ir_attachment"."type" = \'binary\'))  AND  ("ir_attachment"."url" = \'/stock/static/src/less/stock_traceability_report.less\')) ORDER BY "ir_attachment"."id" DESC  limit 1'
ERROR: current transaction is aborted, commands ignored until end of transaction block
 
2018-10-08 07:49:35,096 1 ERROR open7 odoo.sql_db: bad query: b"\n             SELECT max(id)\n               FROM ir_attachment\n              WHERE create_uid = 1\n                AND url like '/web/content/%-8ad3f7f/web.assets_common.%.css'\n           GROUP BY datas_fname\n           ORDER BY datas_fname\n         "
ERROR: current transaction is aborted, commands ignored until end of transaction block
 
2018-10-08 07:49:35,096 1 ERROR open7 odoo.sql_db: bad query: b'SELECT "ir_ui_view".id FROM "ir_ui_view" WHERE (("ir_ui_view"."active" = true)  AND  ("ir_ui_view"."key" = \'web.login_layout\')) ORDER BY "ir_ui_view"."priority" ,"ir_ui_view"."name" ,"ir_ui_view"."id"  '
ERROR: current transaction is aborted, commands ignored until end of transaction block
 
2018-10-08 07:49:35,183 1 INFO open7 werkzeug: 172.17.0.1 - - [08/Oct/2018 07:49:35] "GET /web/login HTTP/1.1" 500 - 85 0.726 2.224
2018-10-08 07:49:35,188 1 ERROR open7 werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 255, in app
    return self.app(e, s)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 128, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1317, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1290, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python3/dist-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1485, in dispatch
    result = ir_http._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
    return super(Http, cls)._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/web_editor/models/ir_http.py", line 22, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/http_routing/models/ir_http.py", line 394, in _dispatch
    result = super(IrHttp, cls)._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/utm/models/ir_http.py", line 26, in _dispatch
    response = super(IrHttp, cls)._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 207, in _dispatch
    return cls._handle_exception(e)
  File "/usr/lib/python3/dist-packages/odoo/addons/utm/models/ir_http.py", line 31, in _handle_exception
    response = super(IrHttp, cls)._handle_exception(exc)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 177, in _handle_exception
    return request._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 773, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 203, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 832, in dispatch
    r = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 340, in checked_call
    result.flatten()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1267, in flatten
    self.response.append(self.render())
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1260, in render
    return env["ir.ui.view"].render_template(self.template, self.qcontext)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 1269, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/usr/lib/python3/dist-packages/odoo/addons/web_editor/models/ir_ui_view.py", line 27, in render
    return super(IrUiView, self).render(values=values, engine=engine, minimal_qcontext=minimal_qcontext)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 1278, in render
    return self.env[engine].render(self.id, qcontext)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_qweb.py", line 59, in render
    result = super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 272, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 346, in _compiled_fn
    raise e
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 344, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_161_5
    
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 349, in _compiled_fn
    element, document = self.get_template(template, options)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 374, in get_template
    raise QWebException("load could not load template", name=template)
odoo.addons.base.models.qweb.QWebException: None
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 88, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.qweb', <function IrQWeb._get_asset_nodes at 0x7f816dad2620>, 'web.assets_common', 'de_AT', True, False, None, False, (None,))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 344, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_web_login_layout_11
  File "<template>", line 2, in body_call_content_10
  File "<template>", line 4, in set_8
  File "<decorator-gen-56>", line 2, in _get_asset_nodes
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 93, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_qweb.py", line 308, in _get_asset_nodes
    return remains + asset.to_node(css=css, js=js, debug=debug, async_load=async_load)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/assetsbundle.py", line 159, in to_node
    css_attachments = self.css() or []
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/assetsbundle.py", line 331, in css
    attachments = self.get_attachments('css')
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/assetsbundle.py", line 272, in get_attachments
    """, [SUPERUSER_ID, url_pattern])
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.InternalError: current transaction is aborted, commands ignored until end of transaction block


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/qweb.py", line 370, in get_template
    document = options.get('load', self.load)(template, options)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_qweb.py", line 122, in load
    template = env['ir.ui.view'].read_template(name)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 1163, in read_template
    return self._read_template(self.get_view_id(xml_id))
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_ui_view.py", line 1175, in get_view_id
    view = self.search([('key', '=', template)])
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1553, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4053, in _search
    self._cr.execute(query_str, where_clause_params)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.InternalError: current transaction is aborted, commands ignored until end of transaction block


load could not load template
Template: web.login_layout - - -

```

**Comment by d-fence** [comment]
What is the version ?
Did you make an upgrade ?

**Comment by lathama** [comment]
@open7c can you provide any information? If you don't need this issue please close it.
