### ISSUE TITLE
error when odoo12 run in docker of synology 

### ISSUE THREAD

**Issue by icegs** [odoo/docker#221]
1.download odoo12 docker  official verision and install with default pararmeters
2.visit odoo in IE，tips are as follows
      Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application
3.logs are as follows，is there any method to fix it？
    date	stream	content
2018-10-14 10:08:47	stdout	TCP/IP connections on port 5432? - - -
2018-10-14 10:08:47	stdout	Is the server running on host "db" (111.63.112.254) and accepting
2018-10-14 10:08:47	stdout	psycopg2.OperationalError: could not connect to server: Connection timed out
2018-10-14 10:08:47	stdout	    conn = _connect(dsn, connection_factory=connection_factory, async=async)
2018-10-14 10:08:47	stdout	  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 164, in connect
2018-10-14 10:08:47	stdout	    **connection_info)
2018-10-14 10:08:47	stdout	  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 608, in borrow
2018-10-14 10:08:47	stdout	    return fun(self, *args, **kwargs)
2018-10-14 10:08:47	stdout	  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 540, in _locked
2018-10-14 10:08:47	stdout	    self._cnx = pool.borrow(dsn)
2018-10-14 10:08:47	stdout	  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 171, in __init__
2018-10-14 10:08:47	stdout	    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
2018-10-14 10:08:47	stdout	  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 657, in cursor
2018-10-14 10:08:47	stdout	    with closing(db.cursor()) as cr:
2018-10-14 10:08:47	stdout	  File "/usr/lib/python3/dist-packages/odoo/service/db.py", line 375, in list_dbs
2018-10-14 10:08:47	stdout	    dbs = odoo.service.db.list_dbs(force)
2018-10-14 10:08:47	stdout	  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1501, in db_list
2018-10-14 10:08:47	stdout	    dbs = db_list(True, httprequest)
2018-10-14 10:08:47	stdout	  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1534, in db_monodb
2018-10-14 10:08:47	stdout	    httprequest.session.db = db_monodb(httprequest)
2018-10-14 10:08:47	stdout	  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1373, in setup_db
2018-10-14 10:08:47	stdout	    self.setup_db(httprequest)
2018-10-14 10:08:47	stdout	  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1450, in dispatch
2018-10-14 10:08:47	stdout	    return self.app(environ, start_response)
2018-10-14 10:08:47	stdout	  File "/usr/lib/python3/dist-packages/werkzeug/wsgi.py", line 599, in __call__
2018-10-14 10:08:47	stdout	    return self.app(environ, start_wrapped)
2018-10-14 10:08:47	stdout	  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1290, in __call__
2018-10-14 10:08:47	stdout	    return self.dispatch(environ, start_response)
2018-10-14 10:08:47	stdout	  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1317, in __call__
2018-10-14 10:08:47	stdout	    result = odoo.http.root(environ, start_response)
2018-10-14 10:08:47	stdout	  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 117, in application_unproxied
2018-10-14 10:08:47	stdout	    return application_unproxied(environ, start_response)
2018-10-14 10:08:47	stdout	  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 128, in application
2018-10-14 10:08:47	stdout	    return self.app(e, s)
2018-10-14 10:08:47	stdout	  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 255, in app
2018-10-14 10:08:47	stdout	    application_iter = app(environ, start_response)
2018-10-14 10:08:47	stdout	  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 193, in execute
2018-10-14 10:08:47	stdout	    execute(self.server.app)
2018-10-14 10:08:47	stdout	  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 205, in run_wsgi
2018-10-14 10:08:47	stdout	Traceback (most recent call last):
2018-10-14 10:08:47	stdout	2018-10-14 10:08:47,097 1 [1;31m[1;49mERROR[0m ? werkzeug: Error on request:
2018-10-14 10:08:47	stdout	2018-10-14 10:08:47,089 1 [1;32m[1;49mINFO[0m ? werkzeug: 172.17.0.1 - - [14/Oct/2018 10:08:47] "GET /favicon.ico HTTP/1.1" 500 - 0 0.000 [1;31m[1;49m127.241[0m
2018-10-14 10:08:47	stdout	2018-10-14 10:08:47,083 1 [1;32m[1;49mINFO[0m ? odoo.sql_db: Connection to the database failed 
2018-10-14 10:06:39	stdout	TCP/IP connections on port 5432? - - -
2018-10-14 10:06:39	stdout	Is the server running on host "db" (111.63.112.254) and accepting
2018-10-14 10:06:39	stdout	psycopg2.OperationalError: could not connect to server: Connection timed out
2018-10-14 10:06:39	stdout	    conn = _connect(dsn, connection_factory=connection_factory, async=async)
2018-10-14 10:06:39	stdout	  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 164, in connect
2018-10-14 10:06:39	stdout	    **connection_info)
2018-10-14 10:06:39	stdout	  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 608, in borrow
2018-10-14 10:06:39	stdout	    return fun(self, *args, **kwargs)
2018-10-14 10:06:39	stdout	  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 540, in _locked
2018-10-14 10:06:39	stdout	    self._cnx = pool.borrow(dsn)
2018-10-14 10:06:39	stdout	  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 171, in __init__
2018-10-14 10:06:39	stdout	    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
2018-10-14 10:06:39	stdout	  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 657, in cursor
2018-10-14 10:06:39	stdout	    with closing(db.cursor()) as cr:
2018-10-14 10:06:39	stdout	  File "/usr/lib/python3/dist-packages/odoo/service/db.py", line 375, in list_dbs
2018-10-14 10:06:39	stdout	    dbs = odoo.service.db.list_dbs(force)
2018-10-14 10:06:39	stdout	  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1501, in db_list
2018-10-14 10:06:39	stdout	    dbs = db_list(True, httprequest)
2018-10-14 10:06:39	stdout	  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1534, in db_monodb
2018-10-14 10:06:39	stdout	    httprequest.session.db = db_monodb(httprequest)
2018-10-14 10:06:39	stdout	  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1373, in setup_db
2018-10-14 10:06:39	stdout	    self.setup_db(httprequest)
2018-10-14 10:06:39	stdout	  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1450, in dispatch
2018-10-14 10:06:39	stdout	    return self.app(environ, start_response)
2018-10-14 10:06:39	stdout	  File "/usr/lib/python3/dist-packages/werkzeug/wsgi.py", line 599, in __call__
2018-10-14 10:06:39	stdout	    return self.app(environ, start_wrapped)
2018-10-14 10:06:39	stdout	  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1290, in __call__
2018-10-14 10:06:39	stdout	    return self.dispatch(environ, start_response)
2018-10-14 10:06:39	stdout	  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1317, in __call__
2018-10-14 10:06:39	stdout	    result = odoo.http.root(environ, start_response)
2018-10-14 10:06:39	stdout	  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 117, in application_unproxied
2018-10-14 10:06:39	stdout	    return application_unproxied(environ, start_response)
2018-10-14 10:06:39	stdout	  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 128, in application
2018-10-14 10:06:39	stdout	    return self.app(e, s)
2018-10-14 10:06:39	stdout	  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 255, in app
2018-10-14 10:06:39	stdout	    application_iter = app(environ, start_response)
2018-10-14 10:06:39	stdout	  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 193, in execute
2018-10-14 10:06:39	stdout	    execute(self.server.app)
2018-10-14 10:06:39	stdout	  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 205, in run_wsgi
2018-10-14 10:06:39	stdout	Traceback (most recent call last):
2018-10-14 10:06:39	stdout	2018-10-14 10:06:39,354 1 [1;31m[1;49mERROR[0m ? werkzeug: Error on request:
2018-10-14 10:06:39	stdout	2018-10-14 10:06:39,344 1 [1;32m[1;49mINFO[0m ? werkzeug: 172.17.0.1 - - [14/Oct/2018 10:06:39] "GET / HTTP/1.1" 500 - 0 0.000 [1;31m[1;49m132.295[0m
2018-10-14 10:06:39	stdout	2018-10-14 10:06:39,339 1 [1;32m[1;49mINFO[0m ? odoo.sql_db: Connection to the database failed 
2018-10-14 10:04:27	stdout	2018-10-14 10:04:27,045 1 [1;32m[1;49mINFO[0m ? odoo.http: HTTP Configuring static files 
2018-10-14 10:03:18	stdout	2018-10-14 10:03:18,541 1 [1;32m[1;49mINFO[0m ? odoo.service.server: HTTP service (werkzeug) running on odoo12:8069 
2018-10-14 10:03:17	stdout	2018-10-14 10:03:17,850 1 [1;32m[1;49mINFO[0m ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf 
2018-10-14 10:03:17	stdout	2018-10-14 10:03:17,406 1 [1;32m[1;49mINFO[0m ? odoo: database: odoo@db:5432 
2018-10-14 10:03:17	stdout	2018-10-14 10:03:17,405 1 [1;32m[1;49mINFO[0m ? odoo: addons paths: ['/var/lib/odoo/addons/12.0', '/mnt/extra-addons', '/usr/lib/python3/dist-packages/odoo/addons'] 
2018-10-14 10:03:17	stdout	2018-10-14 10:03:17,405 1 [1;32m[1;49mINFO[0m ? odoo: Using configuration file at /etc/odoo/odoo.conf 
2018-10-14 10:03:17	stdout	2018-10-14 10:03:17,404 1 [1;32m[1;49mINFO[0m ? odoo: Odoo version 12.0-20181008

**Comment by icegs** [comment]
Can you help me?

**Comment by my1649** [comment]
whats your postgres version? 
Odoo 12 can only run with >9.4, also when you deploy the postgres, it got to state `-e POSTGRES_DB=postgres` , after these are done, it should be ok.
https://github.com/odoo/odoo/issues/27447#issuecomment-427840100

**Comment by my1649** [comment]
close issue if you have no problem

**Comment by eric2chek** [comment]
try this~
in my side , it work 

![2018-11-01_133000](https://user-images.githubusercontent.com/10214822/47834509-b68b6d80-ddda-11e8-9ad5-dbf7e2f33e17.jpg)

![2018-11-01_133240](https://user-images.githubusercontent.com/10214822/47834518-c0ad6c00-ddda-11e8-9bf1-2de44f71948b.jpg)

**Comment by icegs** [comment]
> whats your postgres version?
> Odoo 12 can only run with >9.4, also when you deploy the postgres, it got to state `-e POSTGRES_DB=postgres` , after these are done, it should be ok.
> [odoo/odoo#27447 (comment)](https://github.com/odoo/odoo/issues/27447#issuecomment-427840100)
postgress version is 9.6
![image](https://user-images.githubusercontent.com/34991886/48208120-18387280-e3ad-11e8-8532-bc7dc542a420.png)

**Comment by icegs** [comment]
> try this~
> in my side , it work
> 
> ![2018-11-01_133000](https://user-images.githubusercontent.com/10214822/47834509-b68b6d80-ddda-11e8-9ad5-dbf7e2f33e17.jpg)
> 
> ![2018-11-01_133240](https://user-images.githubusercontent.com/10214822/47834518-c0ad6c00-ddda-11e8-9bf1-2de44f71948b.jpg)
too bad ,it does't work
it seems that  postgresql didn't work,and there is no postgresql.service,i don't know why
![image](https://user-images.githubusercontent.com/34991886/48208637-3c488380-e3ae-11e8-9ad9-8f7ba96a7b31.png)

**Comment by Ahmed-Elbdrawy** [comment]
Hi @icegs  follow instruction: 

1. docker-compose up --build -d

2. docker-compose exec web bash (will enter odoo service)

3. odoo -i base -d odoo --stop-after-init --db_host=db -r odoo -w odoo  

then enter exit

4. docker-compose down

5. docker-compose up --build

Work Now

**Comment by my1649** [comment]
@icegs Try the latest version of Odoo 12, 20181126. There were some problems for 20181008 as I remember. Please reminded to deploy the Odoo with new variate, `POSTGRES_DB=postgres `

**Comment by d-fence** [comment]
Closing old issue.
Re-open if needed.
