### ISSUE TITLE
[10.0] Creating test database

### ISSUE THREAD

**Issue by ZerNox** [odoo/docker#242]
I get no problems with restoring an old database but however, when creating the test database it always gives me this error, anyone knows what it could be related with?

psql (9.6.11)
Type "help" for help.

tes=# SELECT count(1) FROM "res_lang" WHERE ("res_lang"."active" = true);
 count
-------
     1
(1 row)

```
 odoo.sql_db: bad query: SELECT count(1) FROM "res_lang" WHERE ("res_lang"."active" = true)
2019-02-06 10:00:27,364 42 WARNING tes odoo.modules.loading: Transient module states were reset
2019-02-06 10:00:27,365 42 ERROR tes odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/modules/registry.py", line 83, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/usr/lib/python2.7/dist-packages/odoo/modules/loading.py", line 465, in load_modules
    model._register_hook()
  File "/usr/lib/python2.7/dist-packages/odoo/addons/base/res/res_lang.py", line 81, in _register_hook
    if not self.search_count([]):
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 1493, in search_count
    res = self.search(args, count=True)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 1516, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 4258, in _search
    self._cr.execute(query_str, where_clause_params)
  File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column res_lang.active does not exist
LINE 1: SELECT count(1) FROM "res_lang" WHERE ("res_lang"."active" =...

```

**Comment by d-fence** [comment]
Not enough information to help.
10.0 is not supported anymore as a Docker image.
