### ISSUE TITLE
Connection to the database failed 

### ISSUE THREAD

**Issue by haythamadel82** [odoo/docker#244]
Hi,
I'm new to this and I do not know if I'm doing the right steps.
I'm trying to update module .
1 - Creating Database:
docker run -d -e POSTGRES_USER=admin -e POSTGRES_PASSWORD=admin -e POSTGRES_DB=postgres-2 --name data postgres:latest

2 - Creating Odoo10:
docker run -p 8070:8069 --name odoo10 --link data:db -t odoo:10

I used this command to update module
 docker exec -it odoo10 odoo -d postgres-2 -u module --db_host db --db_password admin

but I get this error:

2019-03-12 14:09:04,908 291 INFO ? odoo: Odoo version 10.0-20181126
2019-03-12 14:09:04,908 291 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf
2019-03-12 14:09:04,908 291 INFO ? odoo: addons paths: ['/var/lib/odoo/addons/10.0', u'/mnt/extra-addons', u'/usr/lib/python2.7/dist-packages/odoo/addons', u'/mnt/custom_addons']
2019-03-12 14:09:04,909 291 INFO ? odoo: database: default@db:default
2019-03-12 14:09:04,911 291 INFO ? odoo.sql_db: Connection to the database failed
Traceback (most recent call last):
  File "/usr/bin/odoo", line 9, in <module>
    odoo.cli.main()
  File "/usr/lib/python2.7/dist-packages/odoo/cli/command.py", line 64, in main
    o.run(args)
  File "/usr/lib/python2.7/dist-packages/odoo/cli/server.py", line 175, in run
    main(args)
  File "/usr/lib/python2.7/dist-packages/odoo/cli/server.py", line 140, in main
    odoo.service.db._create_empty_database(db_name)
  File "/usr/lib/python2.7/dist-packages/odoo/service/db.py", line 82, in _create_empty_database
    with closing(db.cursor()) as cr:
  File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 635, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 177, in __init__
    self._cnx = pool.borrow(dsn)
  File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 518, in _locked
    return fun(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 586, in borrow
    **connection_info)
  File "/usr/lib/python2.7/dist-packages/psycopg2/__init__.py", line 164, in connect
    conn = _connect(dsn, connection_factory=connection_factory, async=async)
psycopg2.OperationalError: FATAL:  password authentication failed for user "odoo"

Someone could help me?
Thank you

**Comment by HarriL** [comment]
Change "postgres:latest" to "postgres:9.4". You probably have too new Postgresql.

**Comment by d-fence** [comment]
Sorry for the late answer.
There is something wrong in databases selection, when you start the Postgresql server, you have to specify the postgres database like `-e POSTGRES_DB=postgres`
This is the database used by postgres itself, it's not the odoo database
In your update line, you use  `odoo -d postgres-2 ` so you tell Odoo to use the same db as postgres.

I close this issue. Just re-open if needed

**Comment by aribudih** [comment]
Dear All,

I have the same case to connect odoo 14 as below:

2021-03-15 07:09:45,120 1270 INFO ? odoo.sql_db: Connection to the database failed 
2021-03-15 07:09:45,123 1270 INFO ? werkzeug: 127.0.0.1 - - [15/Mar/2021 07:09:45] "GET / HTTP/1.1" 500 - 0 0.000 0.007
2021-03-15 07:09:45,129 1270 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/werkzeug/serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File "/OpenObject/odoo_v14/odoo/service/server.py", line 440, in app
    return self.app(e, s)
  File "/OpenObject/odoo_v14/odoo/service/wsgi_server.py", line 124, in application
    return application_unproxied(environ, start_response)
  File "/OpenObject/odoo_v14/odoo/service/wsgi_server.py", line 99, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/OpenObject/odoo_v14/odoo/http.py", line 1295, in __call__
    return self.dispatch(environ, start_response)
  File "/OpenObject/odoo_v14/odoo/http.py", line 1263, in __call__
    return self.app(environ, start_wrapped)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/werkzeug/middleware/shared_data.py", line 260, in __call__
    return self.app(environ, start_response)
  File "/OpenObject/odoo_v14/odoo/http.py", line 1429, in dispatch
    self.setup_db(httprequest)
  File "/OpenObject/odoo_v14/odoo/http.py", line 1352, in setup_db
    httprequest.session.db = db_monodb(httprequest)
  File "/OpenObject/odoo_v14/odoo/http.py", line 1517, in db_monodb
    dbs = db_list(True, httprequest)
  File "/OpenObject/odoo_v14/odoo/http.py", line 1484, in db_list
    dbs = odoo.service.db.list_dbs(force)
  File "/OpenObject/odoo_v14/odoo/service/db.py", line 384, in list_dbs
    with closing(db.cursor()) as cr:
  File "/OpenObject/odoo_v14/odoo/sql_db.py", line 675, in cursor
    return Cursor(self.__pool, self.dbname, self.dsn, serialized=serialized)
  File "/OpenObject/odoo_v14/odoo/sql_db.py", line 248, in __init__
    self._cnx = pool.borrow(dsn)
  File "/OpenObject/odoo_v14/odoo/sql_db.py", line 558, in _locked
    return fun(self, *args, **kwargs)
  File "/OpenObject/odoo_v14/odoo/sql_db.py", line 624, in borrow
    result = psycopg2.connect(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: fe_sendauth: no password supplied - - -

Appreciate your kind sharing...

Thank you
Regards
