### ISSUE TITLE
odoo10 still redirect page select database on ui after init

### ISSUE THREAD

**Issue by phucvinh52** [odoo/docker#248]
Hi teams,
First I thank team for your team develop docker image odoo.
I have a problem.
I have a postgres. I created user,pass and a database
I create a container odoo version 10 (image `odoo:10`) with `--init=base.` use above user,pass,db
And after init done, i use browser to url: localhost:8069 but it's still redirect to localhost:8069/web/database/selector.
and i get logs
```2019-04-22 18:30:41,584 1 INFO ? odoo.addons.report.models.report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf
2019-04-22 18:30:42,162 1 INFO ? odoo.http: HTTP Configuring static files
2019-04-22 18:30:42,197 1 INFO odoo1 odoo.sql_db: bad query: CREATE SEQUENCE base_registry_signaling INCREMENT BY 1 START WITH 1
2019-04-22 18:30:42,200 1 ERROR odoo1 odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/modules/registry.py", line 80, in new
    registry.setup_signaling()
  File "/usr/lib/python2.7/dist-packages/odoo/modules/registry.py", line 377, in setup_signaling
    cr.execute("CREATE SEQUENCE base_registry_signaling INCREMENT BY 1 START WITH 1")
  File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
ProgrammingError: relation "base_registry_signaling" already exists

2019-04-22 18:30:42,204 1 INFO odoo1 odoo.http: Generating nondb routing
2019-04-22 18:30:42,233 1 INFO odoo1 werkzeug: 172.18.0.1 - - [22/Apr/2019 18:30:42] "GET / HTTP/1.1" 200 -```



I try with odoo 11 and 12 without that error

**Comment by ralienpp** [comment]
@phucvinh52, did you manage to solve the problem?

**Comment by d-fence** [comment]
No answer  and Odoo 10 is no longer supported.

**Comment by pouyamn** [comment]
have the same error in 14.0 after restoring a database
