### ISSUE TITLE
Auto-populate company contact error

### ISSUE THREAD

**Issue by Nevyn75** [odoo/docker#260]
Impacted versions: 12

Steps to reproduce:

- Clean container
- Create new DB
- Install Contacts module
- Inside Contacts module create new Company contact
- Type few characters into company name and select one of the suggested company

This error appears:

> Uncaught TypeError: Cannot read property 'type' of undefined
> https://mydomain.com:8443/web/content/382-6ac400c/web.assets_backend.js:1357
> Traceback:
> TypeError: Cannot read property 'type' of undefined
> at Class._applyChange (https://mydomain.com:8443/web/content/382-6ac400c/web.assets_backend.js:1357:205)
> at Object. (https://mydomain.com:8443/web/content/378-30ab706/web.assets_common.js:3751:384)
> at Object. (https://mydomain.com:8443/web/content/378-30ab706/web.assets_common.js:802:681)
> at fire (https://mydomain.com:8443/web/content/378-30ab706/web.assets_common.js:796:299)
> at Object.add [as done] (https://mydomain.com:8443/web/content/378-30ab706/web.assets_common.js:797:467)
> at Array. (https://mydomain.com:8443/web/content/378-30ab706/web.assets_common.js:802:649)
> at Function.each (https://mydomain.com:8443/web/content/378-30ab706/web.assets_common.js:625:767)
> at Object. (https://mydomain.com:8443/web/content/378-30ab706/web.assets_common.js:802:560)
> at Function.Deferred (https://mydomain.com:8443/web/content/378-30ab706/web.assets_common.js:803:194)
> at Object.then (https://mydomain.com:8443/web/content/378-30ab706/web.assets_common.js:802:525)

If I disable auto-populate feature or I don't click on any suggested Company, the contact is created without any problem.

Same test running odoo from fresh source code pull, gives no errors.

Thanks.

**Comment by d-fence** [comment]
Cannot reproduce.
Can you tell if the issue is still present on your side ?

**Comment by lathama** [comment]
@Nevyn75 is this still an issue? If it is you may want to look at the issues on the odoo project and not this docker project. If you do not need this issue any longer can you please close it?
