### ISSUE TITLE
[13.0] Wrong Werkzeug version leads to errors in website builder

### ISSUE THREAD

**Issue by bosskopp** [odoo/docker#299]
odoo:13 docker image, container shell:
```
pip3 show werkzeug
Name: Werkzeug
Version: 0.16.0
```
Odoo 13 requirements file (https://github.com/odoo/odoo/blob/13.0/requirements.txt):
`Werkzeug==0.14.1`

In the DEB that's referenced in the Dockerfile... 
https://github.com/odoo/docker/blob/6d92142da193f60c161f97eea1079f437dd51d7e/13.0/Dockerfile#L56
https://github.com/odoo/docker/blob/6d92142da193f60c161f97eea1079f437dd51d7e/13.0/Dockerfile#L59
... there is no version set for Werkzeug.

```
dpkg-deb -I odoo_13.0.20200121_all.deb 
...
 Package: odoo
 Version: 13.0.20200121
 Architecture: all
 Maintainer: Odoo S.A. <info@odoo.com>
 Installed-Size: 533587
 Depends:  ... python3-werkzeug ...
```

Werkzeug 0.16 (instead of 0.14) leads to errors in website builder, e.g.:

1. Install website builder,
2. Edit a page,
3. Select some text and click the editors _link_ button,
4. Try to enter a link destination in the _URL or E-Mail_ field.

Results in:
```
Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 909, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1319, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1311, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 395, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 382, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/website.py", line 784, in search_pages
    for page in self.enumerate_pages(query_string=name, force=True):
  File "/usr/lib/python3/dist-packages/odoo/addons/website/models/website.py", line 721, in enumerate_pages
    if query_string and not converters and (query_string not in rule.build([{}], append_unknown=False)[1]):
  File "/usr/lib/python3/dist-packages/werkzeug/routing.py", line 977, in build
    return self._build(**values)
TypeError: <builder:'/website/info'>() argument after ** must be a mapping, not list
```

**Comment by Yenthe666** [comment]
@d-fence for you probably
