### ISSUE TITLE
Odoo 13 Community Partner Ledger not working. 

### ISSUE THREAD

**Issue by jackson-rpdcool** [odoo/docker#314]
Hi All

When I try to open Odoo Default Partner Ledger it is not working and giving following error. I do not have any third party modules in my DB now. But if I install to get third party partner ledger it fetches wrong debit and credit report. In some companies ledger paid shows in the report and unpaid dosen't appear at all. If anyone come across such issues please help me to solve it as I am just a beginner 

Error:
Odoo Server Error

Traceback (most recent call last):
  File "C:\odoo\Odoo 13.0\server\odoo\http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\odoo\Odoo 13.0\server\odoo\http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "C:\odoo\Odoo 13.0\server\odoo\tools\pycompat.py", line 14, in reraise
    raise value
  File "C:\odoo\Odoo 13.0\server\odoo\http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "C:\odoo\Odoo 13.0\server\odoo\http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\odoo\Odoo 13.0\server\odoo\service\model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\odoo\Odoo 13.0\server\odoo\http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\odoo\Odoo 13.0\server\odoo\http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "C:\odoo\Odoo 13.0\server\odoo\http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "C:\odoo\Odoo 13.0\server\odoo\addons\web\controllers\main.py", line 1320, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "C:\odoo\Odoo 13.0\server\odoo\addons\web\controllers\main.py", line 1312, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\odoo\Odoo 13.0\server\odoo\api.py", line 383, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "C:\odoo\Odoo 13.0\server\odoo\api.py", line 356, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "C:\odoo\Odoo 13.0\server\odoo\addons\web\models\models.py", line 75, in web_read_group
    expand_limit, expand_orderby)
  File "C:\odoo\Odoo 13.0\server\odoo\addons\web\models\models.py", line 99, in _web_read_group
    orderby=orderby, lazy=lazy)
  File "C:\odoo\Odoo 13.0\server\odoo\models.py", line 2140, in read_group
    result = self._read_group_raw(domain, fields, groupby, offset=offset, limit=limit, orderby=orderby, lazy=lazy)
  File "C:\odoo\Odoo 13.0\server\odoo\models.py", line 2177, in _read_group_raw
    assert gb_field.store and gb_field.column_type, "Fields in 'groupby' must be regular database-persisted fields (no function or related fields), or function fields with store=True"
AssertionError: Fields in 'groupby' must be regular database-persisted fields (no function or related fields), or function fields with store=True

**Comment by lathama** [comment]
@jackson-rpdcool are you able to test this against Odoo 17 or any recent versions? This might be an issue for https://github.com/odoo/odoo instead of the docker repo. If this is no longer an issue please close this issue.
