### ISSUE TITLE
column "datas_fname" does not exist odoo:11.0

### ISSUE THREAD

**Issue by topherbuckley** [odoo/docker#317]
I setup and ran the 13.0 image using the [tutorial](https://registry.hub.docker.com/_/odoo/) without issues, but now trying the 11.0 image using the same steps I am having an issue. Is there different database requirements for 11.0 compared to 13.0? If so, is there documentation specific to 11.0 somewhere I could reference? 

Running:

`docker run -p 8069:8069 --name odoo --link db:db -t odoo:11.0`

results in the normal startup and run sequences:

>2020-08-02 05:55:07,377 1 INFO ? odoo: Odoo version 11.0-20200629
2020-08-02 05:55:07,377 1 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf
2020-08-02 05:55:07,378 1 INFO ? odoo: addons paths: ['/var/lib/odoo/addons/11.0', '/mnt/extra-addons', '/usr/lib/python3/dist-packages/odoo/addons']
2020-08-02 05:55:07,378 1 INFO ? odoo: database: odoo@172.17.0.2:5432
2020-08-02 05:55:07,400 1 INFO ? odoo.service.server: HTTP service (werkzeug) running on e4125c6711f9:8069
2020-08-02 05:55:07,534 1 INFO ? odoo.addons.base.ir.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf

But upon trying to access `localhost:8069` from my browser, I get:

>Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

On the output of my terminal I get:

>2020-08-02 05:55:07,377 1 INFO ? odoo: Odoo version 11.0-20200629
2020-08-02 05:55:07,377 1 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf
2020-08-02 05:55:07,378 1 INFO ? odoo: addons paths: ['/var/lib/odoo/addons/11.0', '/mnt/extra-addons', '/usr/lib/python3/dist-packages/odoo/addons']
2020-08-02 05:55:07,378 1 INFO ? odoo: database: odoo@172.17.0.2:5432
2020-08-02 05:55:07,400 1 INFO ? odoo.service.server: HTTP service (werkzeug) running on e4125c6711f9:8069
2020-08-02 05:55:07,534 1 INFO ? odoo.addons.base.ir.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf
2020-08-02 05:55:59,958 1 INFO ? odoo.http: HTTP Configuring static files
2020-08-02 05:55:59,975 1 INFO test odoo.modules.loading: loading 1 modules...
2020-08-02 05:55:59,994 1 INFO test odoo.modules.loading: 1 modules loaded in 0.02s, 0 queries
2020-08-02 05:55:59,998 1 WARNING test odoo.modules.graph: module web_unsplash: not installable, skipped
2020-08-02 05:56:00,011 1 WARNING test odoo.modules.graph: module partner_autocomplete: not installable, skipped
2020-08-02 05:56:00,012 1 WARNING test odoo.modules.graph: module hr_holidays_calendar: not installable, skipped
2020-08-02 05:56:00,014 1 WARNING test odoo.modules.graph: module mail_bot: not installable, skipped
2020-08-02 05:56:00,015 1 WARNING test odoo.modules.graph: module snailmail: not installable, skipped
2020-08-02 05:56:00,021 1 WARNING test odoo.modules.graph: module odoo_referral: not installable, skipped
2020-08-02 05:56:00,027 1 INFO test odoo.modules.loading: loading 23 modules...
2020-08-02 05:56:00,130 1 INFO test odoo.modules.loading: 23 modules loaded in 0.10s, 0 queries
2020-08-02 05:56:00,422 1 INFO test odoo.modules.loading: Modules loaded.
2020-08-02 05:56:00,427 1 INFO test odoo.addons.base.ir.ir_http: Generating routing map
2020-08-02 05:56:00,484 1 INFO test werkzeug: 172.17.0.1 - - [02/Aug/2020 05:56:00] "GET / HTTP/1.1" 303 -
2020-08-02 05:56:00,505 1 INFO test werkzeug: 172.17.0.1 - - [02/Aug/2020 05:56:00] "GET /web HTTP/1.1" 303 -
2020-08-02 05:56:00,835 1 ERROR test odoo.sql_db: bad query: 
             SELECT max(id)
               FROM ir_attachment
              WHERE create_uid = 1
                AND url like '/web/content/%-cecf5ab/web.assets_common.%.css'
           GROUP BY datas_fname
           ORDER BY datas_fname  
ERROR: column "datas_fname" does not exist
LINE 7:            ORDER BY datas_fname
                            ^
2020-08-02 05:56:01,041 1 INFO test werkzeug: 172.17.0.1 - - [02/Aug/2020 05:56:01] "GET /web/login HTTP/1.1" 500 -
2020-08-02 05:56:01,049 1 ERROR test werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/server.py", line 348, in app
    return self.app(e, s)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 180, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1321, in __call__
    return self.dispatch(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1295, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/lib/python3/dist-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1493, in dispatch
    result = ir_http._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
    return super(Http, cls)._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/web_editor/models/ir_http.py", line 22, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_http.py", line 212, in _dispatch
    return cls._handle_exception(e)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_http.py", line 182, in _handle_exception
    return request._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 773, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_http.py", line 208, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 832, in dispatch
    r = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 340, in checked_call
    result.flatten()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1272, in flatten
    self.response.append(self.render())
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1265, in render
    return env["ir.ui.view"].render_template(self.template, self.qcontext)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 1230, in render_template
    return self.browse(self.get_view_id(template)).render(values, engine)
  File "/usr/lib/python3/dist-packages/odoo/addons/web_editor/models/ir_ui_view.py", line 27, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_ui_view.py", line 1239, in render
    return self.env[engine].render(self.id, qcontext)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 57, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 275, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 348, in _compiled_fn
    raise e
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 346, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_196_5
    
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 348, in _compiled_fn
    raise e
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 346, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_web_login_layout_10
    
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 353, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
**odoo.addons.base.ir.ir_qweb.qweb.QWebException:** **column** **"datas_fname"** **does** **not** **exist**
LINE 7:            ORDER BY datas_fname
                            ^

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 84, in lookup
    r = d[key]
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 68, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.qweb', <function IrQWeb._get_asset_nodes at 0x7f4cad054a60>, 'web.assets_common', 'en_US', True, False, None, False, False, (None,))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 346, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_web_frontend_layout_25
  File "<decorator-gen-39>", line 2, in _get_asset_nodes
  File "/usr/lib/python3/dist-packages/odoo/tools/cache.py", line 89, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 302, in _get_asset_nodes
    return remains + asset.to_node(css=css, js=js, debug=debug, async_load=async_load)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_qweb/assetsbundle.py", line 153, in to_node
    css_attachments = self.css() or []
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_qweb/assetsbundle.py", line 281, in css
    attachments = self.get_attachments('css')
  File "/usr/lib/python3/dist-packages/odoo/addons/base/ir/ir_qweb/assetsbundle.py", line 237, in get_attachments
    """, [SUPERUSER_ID, url_pattern])
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: column "datas_fname" does not exist
LINE 7:            ORDER BY datas_fname
                            ^
Error to render compiling AST
ProgrammingError: column "datas_fname" does not exist
LINE 7:            ORDER BY datas_fname
                            ^
Template: web.frontend_layout
Path: /templates/t/html/head/t[1]
Node: <t t-call-assets="web.assets_common" t-js="false"/>
2020-08-02 05:56:07,736 1 WARNING ? odoo.addons.base.ir.ir_cron: Skipping database test as its base version is not 11.0.1.3.
2020-08-02 05:56:08,727 1 WARNING ? odoo.addons.base.ir.ir_cron: Skipping database test as its base version is not 11.0.1.3.

**Comment by topherbuckley** [comment]
After restarting the db container, this error seems to have been resolved.
