### ISSUE TITLE
Cannot Connect to odoo after performing a deployment on k8s and restoring our SAAS DB 

### ISSUE THREAD

**Issue by mrad-bilel** [odoo/docker#371]
Hey,

I've successfully deployed odoo on kubernetes using odoo docker image v14 . Then i've restored my SAAS DB to an RDS DB instance , after that i cannot login to odoo using the GUI .

```
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:42.93717327Z 2021-05-31 11:02:42,937 1 WARNING odoo odoo.modules.module: module web_mobile: module not found 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:42.938599368Z 2021-05-31 11:02:42,938 1 WARNING odoo odoo.modules.module: module web_mobile: module not found 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:42.940069385Z 2021-05-31 11:02:42,939 1 WARNING odoo odoo.modules.module: module web_mobile: module not found 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:42.941491325Z 2021-05-31 11:02:42,941 1 WARNING odoo odoo.modules.module: module web_mobile: module not found 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:42.942963762Z 2021-05-31 11:02:42,942 1 WARNING odoo odoo.modules.module: module web_mobile: module not found 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:42.944780176Z 2021-05-31 11:02:42,944 1 WARNING odoo odoo.modules.module: module web_mobile: module not found 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:42.945822813Z 2021-05-31 11:02:42,945 1 WARNING odoo odoo.modules.module: module web_mobile: module not found 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:42.947259035Z 2021-05-31 11:02:42,947 1 WARNING odoo odoo.modules.module: module web_mobile: module not found 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:42.949006249Z 2021-05-31 11:02:42,948 1 WARNING odoo odoo.modules.module: module web_mobile: module not found 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:42.950510981Z 2021-05-31 11:02:42,950 1 WARNING odoo odoo.modules.module: module web_mobile: module not found 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:42.952355064Z 2021-05-31 11:02:42,951 1 WARNING odoo odoo.modules.module: module web_mobile: module not found 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:42.953625594Z 2021-05-31 11:02:42,952 1 WARNING odoo odoo.modules.module: module web_cohort: module not found 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:42.955337268Z 2021-05-31 11:02:42,954 1 WARNING odoo odoo.modules.module: module web_cohort: module not found 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:42.955887344Z 2021-05-31 11:02:42,955 1 WARNING odoo odoo.modules.module: module web_cohort: module not found 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:42.957324841Z 2021-05-31 11:02:42,957 1 WARNING odoo odoo.modules.module: module web_cohort: module not found 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:42.959132642Z 2021-05-31 11:02:42,958 1 WARNING odoo odoo.modules.module: module web_cohort: module not found 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:42.960269886Z 2021-05-31 11:02:42,960 1 WARNING odoo odoo.modules.module: module web_enterprise: module not found 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:42.961791492Z 2021-05-31 11:02:42,961 1 WARNING odoo odoo.modules.module: module web_enterprise: module not found 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:42.963452999Z 2021-05-31 11:02:42,963 1 WARNING odoo odoo.modules.module: module web_enterprise: module not found 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:42.965244482Z 2021-05-31 11:02:42,964 1 WARNING odoo odoo.modules.module: module web_enterprise: module not found 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:42.966828265Z 2021-05-31 11:02:42,966 1 WARNING odoo odoo.modules.module: module web_enterprise: module not found 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:42.968718447Z 2021-05-31 11:02:42,967 1 WARNING odoo odoo.modules.module: module web_enterprise: module not found 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:42.969400661Z 2021-05-31 11:02:42,969 1 WARNING odoo odoo.modules.module: module web_enterprise: module not found 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:42.971922443Z 2021-05-31 11:02:42,970 1 WARNING odoo odoo.modules.module: module web_enterprise: module not found 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:42.972688248Z 2021-05-31 11:02:42,972 1 WARNING odoo odoo.modules.module: module web_enterprise: module not found 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:42.975773095Z 2021-05-31 11:02:42,973 1 WARNING odoo odoo.modules.module: module web_enterprise: module not found 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:42.975786042Z 2021-05-31 11:02:42,975 1 WARNING odoo odoo.modules.module: module web_enterprise: module not found 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:42.977196468Z 2021-05-31 11:02:42,976 1 WARNING odoo odoo.modules.module: module web_enterprise: module not found 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:42.978572317Z 2021-05-31 11:02:42,978 1 WARNING odoo odoo.modules.module: module web_enterprise: module not found 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:42.980036795Z 2021-05-31 11:02:42,979 1 WARNING odoo odoo.modules.module: module web_enterprise: module not found 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:42.981157862Z 2021-05-31 11:02:42,981 1 WARNING odoo odoo.modules.module: module web_enterprise: module not found 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:42.98331648Z 2021-05-31 11:02:42,982 1 WARNING odoo odoo.modules.module: module web_enterprise: module not found 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:42.984237464Z 2021-05-31 11:02:42,984 1 WARNING odoo odoo.modules.module: module web_enterprise: module not found 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:42.985688425Z 2021-05-31 11:02:42,985 1 WARNING odoo odoo.modules.module: module web_enterprise: module not found 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:42.98749665Z 2021-05-31 11:02:42,987 1 WARNING odoo odoo.modules.module: module web_enterprise: module not found 
```
```
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.772945192Z 2021-05-31 11:02:44,772 1 INFO odoo odoo.addons.base.models.ir_attachment: _read_file reading /var/lib/odoo/.local/share/Odoo/filestore/odoo/4d/4d4d367cbf3f00a013a7007b4e65d5a9ac84bf8e 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.772990211Z Traceback (most recent call last):
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.772995869Z   File "/usr/lib/python3/dist-packages/odoo/api.py", line 789, in get
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.772999766Z     field_cache = field_cache[record.env.cache_key(field)]
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.773003308Z KeyError: (None, None)
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.773006362Z 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.773009929Z During handling of the above exception, another exception occurred:
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.773013183Z 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.773015999Z Traceback (most recent call last):
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.773019173Z   File "/usr/lib/python3/dist-packages/odoo/fields.py", line 970, in __get__
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.773022446Z     value = env.cache.get(record, self)
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.773025524Z   File "/usr/lib/python3/dist-packages/odoo/api.py", line 793, in get
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.773028733Z     raise CacheMiss(record, field)
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.773034148Z odoo.exceptions.CacheMiss: 'ir.attachment(621,).datas'
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.773037338Z 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.773040306Z During handling of the above exception, another exception occurred:
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.773053967Z 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.773056975Z Traceback (most recent call last):
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.773060114Z   File "/usr/lib/python3/dist-packages/odoo/api.py", line 789, in get
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.773063423Z     field_cache = field_cache[record.env.cache_key(field)]
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.773066695Z KeyError: (None,)
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.773070409Z 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.773073616Z During handling of the above exception, another exception occurred:
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.773077083Z 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.773080411Z Traceback (most recent call last):
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.773083383Z   File "/usr/lib/python3/dist-packages/odoo/fields.py", line 970, in __get__
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.773086822Z     value = env.cache.get(record, self)
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.773089846Z   File "/usr/lib/python3/dist-packages/odoo/api.py", line 793, in get
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.773092888Z     raise CacheMiss(record, field)
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.773096068Z odoo.exceptions.CacheMiss: 'ir.attachment(621,).raw'
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.773099534Z 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.773102168Z During handling of the above exception, another exception occurred:
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.773105168Z 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.773107951Z Traceback (most recent call last):
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.773111352Z   File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_attachment.py", line 102, in _file_read
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.773114784Z     with open(full_path, 'rb') as f:
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.773118064Z FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/.local/share/Odoo/filestore/odoo/4d/4d4d367cbf3f00a013a7007b4e65d5a9ac84bf8e'
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.776073574Z 2021-05-31 11:02:44,775 1 INFO odoo werkzeug: 192.168.101.99 - - [31/May/2021 11:02:44] "GET /web/content/621-62a9238/web.assets_common.css HTTP/1.1" 404 - 2 0.010 0.012
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.869515215Z 2021-05-31 11:02:44,869 1 INFO odoo odoo.addons.base.models.ir_attachment: _read_file reading /var/lib/odoo/.local/share/Odoo/filestore/odoo/6b/6b3dd40c7d8933ecd7fc85d0e6dcc7e9e100f4af 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.869614854Z Traceback (most recent call last):
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.870566441Z   File "/usr/lib/python3/dist-packages/odoo/api.py", line 789, in get
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.870578439Z     field_cache = field_cache[record.env.cache_key(field)]
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.870582896Z KeyError: (None, None)
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.870586196Z 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.870589506Z During handling of the above exception, another exception occurred:
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.870593569Z 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.870596983Z Traceback (most recent call last):
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.870600433Z   File "/usr/lib/python3/dist-packages/odoo/fields.py", line 970, in __get__
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.870604109Z     value = env.cache.get(record, self)
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.870616124Z   File "/usr/lib/python3/dist-packages/odoo/api.py", line 793, in get
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.870620028Z     raise CacheMiss(record, field)
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.870623284Z odoo.exceptions.CacheMiss: 'ir.attachment(622,).datas'
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.870626468Z 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.870629771Z During handling of the above exception, another exception occurred:
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.870633692Z 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.870636902Z Traceback (most recent call last):
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.87064026Z   File "/usr/lib/python3/dist-packages/odoo/api.py", line 789, in get
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.870643953Z     field_cache = field_cache[record.env.cache_key(field)]
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.870647703Z KeyError: (None,)
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.870651019Z 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.870654223Z During handling of the above exception, another exception occurred:
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.87065809Z 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.87066133Z Traceback (most recent call last):
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.870664659Z   File "/usr/lib/python3/dist-packages/odoo/fields.py", line 970, in __get__
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.870668001Z     value = env.cache.get(record, self)
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.870671334Z   File "/usr/lib/python3/dist-packages/odoo/api.py", line 793, in get
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.870674861Z     raise CacheMiss(record, field)
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.870678152Z odoo.exceptions.CacheMiss: 'ir.attachment(622,).raw'
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.870681517Z 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.870684658Z During handling of the above exception, another exception occurred:
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.870688208Z 
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.870691344Z Traceback (most recent call last):
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.870694804Z   File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_attachment.py", line 102, in _file_read
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.870698633Z     with open(full_path, 'rb') as f:
odoo-c9d7fd4c5-bzph9 odoo 2021-05-31T11:02:44.870702096Z FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/odoo/.local/share/Odoo/filestore/odoo/6b/6b3dd40c7d8933ecd7fc85d0e6dcc7e9e100f4af'

```

Any idea please how to fix this issue . 

Bilel

**Comment by mrad-bilel** [comment]
Any update .

**Comment by mrad-bilel** [comment]
Any update .

**Comment by mrad-bilel** [comment]
Any update .

**Comment by d-fence** [comment]
Hello, sorry but there is not enough information to try to reproduce your issue.
By looking at the logs you provided:
`module web_enterprise: module not found` it seems that your addons are not present. Maybe a volume not mounted ?

**Comment by mrad-bilel** [comment]
I've fixed this issue and my deployment works fine but i got another issue when i login i see a blank page , and the below error from the web browser consol 

```
the server responded with a status of 404 (NOT FOUND) web.assets_frontend.css:1 Failed to load resource: the server responded with a status of 404 (NOT FOUND) web.assets_common_minimal_js.js:1 Failed to load resource: the server responded with a status of 404 (NOT FOUND) web.assets_frontend_minimal_js.js:1 Failed to load resource
```

**Comment by akhemar** [comment]
Try to add this command to your deployment: odoo -u website -d db_name
```
...
spec:
  containers:
  - name: odoo_container_name
    image: odoo
    command: ["odoo", "-u", "website", "-d", "db_name"]
...
```
This will update the module "website" and all modules depending on it to regenerate frontend assets (css & js). Then, you shoud have the missing file from your filestore (web.assets_frontend_minimal_js.js).
If it works, try to remember to stop & remove the commad from deployment and start it again, else, try to update "web" module.

**Comment by aliencrash** [comment]
@mrad-bilel  
Did you had issues with assets after moving to k8s? Like sometimes the backend doesn't open because of the  javascript being cut?

**Comment by mrad-bilel** [comment]
@aliencrash  sorry for the delay in my response I've had a lot of problem when moving to k8s as there is no documents , what is you problem I'll try to help in I can .
