### ISSUE TITLE
Create button and download buttons not working

### ISSUE THREAD

**Issue by jackmacha** [odoo/docker#407]
AttributeError: 'NoneType' object has no attribute 'WorkbookError:
Odoo Server Error

Traceback (most recent call last):
  File "/home/macha/odoo/addons/web/controllers/main.py", line 111, in wrap
    return f(*args, **kwargs)
  File "/home/macha/odoo/addons/web/controllers/main.py", line 2005, in index
    return self.base(data, token)
  File "/home/macha/odoo/addons/web/controllers/main.py", line 1957, in base
    response_data = self.from_data(columns_headers, export_data)
  File "/home/macha/odoo/addons/web/controllers/main.py", line 2023, in from_data
    with ExportXlsxWriter(fields, len(rows)) as xlsx_writer:
  File "/home/macha/odoo/addons/web/controllers/main.py", line 773, in __init__
    self.workbook = xlsxwriter.Workbook(self.output, {'in_memory': True})
AttributeError: 'NoneType' object has no attribute 'Workbook'

**Comment by JDSalcedo** [comment]
You have to install the dependency `xlsxwriter`, take a look the `requirements.txt` file to know the exact version.

**Comment by jackmacha** [comment]
Thanks... This helped me out

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by lathama** [comment]
@jackmacha can you close this issue if no longer needed?

**Comment by jackmacha** [comment]
Closed

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
