### ISSUE TITLE
Error when creating new user

### ISSUE THREAD

**Issue by Etren** [odoo/docker#416]
I get this error when I create user with odoo running inside docker.

```UncaughtPromiseError > SyntaxError
Uncaught Promise > Failed to execute 'querySelectorAll' on 'Element': '"]' is not a valid selector.
SyntaxError: Failed to execute 'querySelectorAll' on 'Element': '"]' is not a valid selector.
    at classToStyle (https://my.domain.com:63620/web/assets/118-420afd0/web.assets_backend.min.js:9622:192)
    at toInline (https://my.domain.com:63620/web/assets/118-420afd0/web.assets_backend.min.js:9635:179)
    at Class._toInline (https://my.domain.com:63620/web/assets/118-420afd0/web.assets_backend.min.js:9690:231)
    at Class.commitChanges (https://my.domain.com:63620/web/assets/118-420afd0/web.assets_backend.min.js:9689:107)
    at Class.commitChanges (https://my.domain.com:63620/web/assets/115-13a047e/web.assets_common.min.js:4728:371)
    at https://my.domain.com:63620/web/assets/118-420afd0/web.assets_backend.min.js:4772:250
    at _.map._.collect (https://my.domain.com:63620/web/assets/115-13a047e/web.assets_common.min.js:154:270)
    at Class.commitChanges (https://my.domain.com:63620/web/assets/118-420afd0/web.assets_backend.min.js:4772:184)
    at https://my.domain.com:63620/web/assets/118-420afd0/web.assets_backend.min.js:4503:659```

**Comment by v3ss0n** [comment]
I am facing this too on odoo 16
