### ISSUE TITLE
Error : Relational field "mail.thread/messagefailed" targets to unknown model name "mail.message.failed"

### ISSUE THREAD

**Issue by foliveira-gol** [odoo/docker#419]
Hi,

Since Odoo 14.0-20220708 version, I have the following error : 
`Erreur:
Retraçage :
Error: Relational field "mail.thread/messagefailed" targets to unknown model name "mail.message.failed".
    at ModelManager._checkDeclaredFieldsOnModels (https://xxx/web/content/1006-5bab876/web.assets_backend.js:4580:29)
    at ModelManager._generateModels (https://xxx/web/content/1006-5bab876/web.assets_backend.js:4682:6)
    at ModelManager.start (https://xxx/web/content/1006-5bab876/web.assets_backend.js:4556:44)
    at createMessaging (https://xxx/web/content/54-5da9edd/web.assets_backend_prod_only.js:7:415)`

It works perfectly in version Odoo 14.0-20220520 and not with versions 14.0-20220708 and 14.0-20220819

Best Regards.

**Comment by foliveira-gol** [comment]
Problem resolved. 
Plugin mail_tracking (https://github.com/OCA/social/tree/14.0/mail_tracking )generate the error. I have updated the plugin and now it works
