### ISSUE TITLE
UncaughtPromiseError > OwlError Promesse non interceptée > Invalid prop suffix

### ISSUE THREAD

**Issue by barzag** [odoo/docker#443]
Hello everyone.

I need help, I have an error on my Odoo Docker 16.0.
I can no longer access modules such as invoicing, settings, sales...

Here is the error message that appears.

`OwlError:` Invalid prop suffix
    at CodeGenerator.formatProp (https://odoo.alfagroup.fr/web/assets/183-d5e93cc/web.assets_common.min.js:1787:12)
    at https://odoo.alfagroup.fr/web/assets/183-d5e93cc/web.assets_common.min.js:1789:68
    at Array.map (<anonymous>)
    at CodeGenerator.formatPropObject (https://odoo.alfagroup.fr/web/assets/183-d5e93cc/web.assets_common.min.js:1789:50)
    at CodeGenerator.compileComponent (https://odoo.alfagroup.fr/web/assets/183-d5e93cc/web.assets_common.min.js:1792:113)
    at CodeGenerator.compileAST (https://odoo.alfagroup.fr/web/assets/183-d5e93cc/web.assets_common.min.js:1684:558)
    at CodeGenerator.compileTDomNode (https://odoo.alfagroup.fr/web/assets/183-d5e93cc/web.assets_common.min.js:1720:368)
    at CodeGenerator.compileAST (https://odoo.alfagroup.fr/web/assets/183-d5e93cc/web.assets_common.min.js:1684:140)
    at CodeGenerator.compileTIfBranch (https://odoo.alfagroup.fr/web/assets/183-d5e93cc/web.assets_common.min.js:1736:101)
    at CodeGenerator.compileTIf (https://odoo.alfagroup.fr/web/assets/183-d5e93cc/web.assets_common.min.js:1740:59)``

What should I do? I am completely stuck.

Thank you. :)

**Comment by tgauges** [comment]
I had the same problem and fixed it by upgrading the module `base`.
In terms of Docker this means running something like `docker run ... -u base ...`.

**Comment by ahobbit** [comment]
I am facing the same problem, I've the latest docker image, and I'm using the docker-compose.yml

**Comment by jacobmason** [comment]
Same problem here. Tried upgrading the module base, but it didn't help.

**Comment by DoumeDuSud** [comment]
I have the same problem with the .deb package.

**This issue is very serious because almost all action button not working** for exemple in Project, nothing could be created

```
odoo --version
Odoo Server 16.0-20230404
```

Error message : 

```
UncaughtPromiseError > OwlError

Promesse non interceptée > Invalid prop suffix

OwlError: Invalid prop suffix
    OwlError@http://192.168.1.30:8069/web/assets/454-e79ddd1/web.assets_common.min.js:1205:1
    formatProp@http://192.168.1.30:8069/web/assets/454-e79ddd1/web.assets_common.min.js:1859:12
    formatPropObject/<@http://192.168.1.30:8069/web/assets/454-e79ddd1/web.assets_common.min.js:1861:68
    formatPropObject@http://192.168.1.30:8069/web/assets/454-e79ddd1/web.assets_common.min.js:1861:50
    compileComponent@http://192.168.1.30:8069/web/assets/454-e79ddd1/web.assets_common.min.js:1864:113
    compileAST@http://192.168.1.30:8069/web/assets/454-e79ddd1/web.assets_common.min.js:1756:558
    compileTDomNode@http://192.168.1.30:8069/web/assets/454-e79ddd1/web.assets_common.min.js:1792:368
    compileAST@http://192.168.1.30:8069/web/assets/454-e79ddd1/web.assets_common.min.js:1756:140
    generateCode@http://192.168.1.30:8069/web/assets/454-e79ddd1/web.assets_common.min.js:1732:113
    compile@http://192.168.1.30:8069/web/assets/454-e79ddd1/web.assets_common.min.js:2001:348
    _compileTemplate@http://192.168.1.30:8069/web/assets/454-e79ddd1/web.assets_common.min.js:2052:280
    _compileTemplate@http://192.168.1.30:8069/web/assets/454-e79ddd1/web.assets_common.min.js:2062:83
    getTemplate@http://192.168.1.30:8069/web/assets/454-e79ddd1/web.assets_common.min.js:1666:118
    callTemplate@http://192.168.1.30:8069/web/assets/454-e79ddd1/web.assets_common.min.js:1669:68
    template@http://192.168.1.30:8069/web/assets/454-e79ddd1/web.assets_common.min.js line 2001 > Function:9:12
    _render@http://192.168.1.30:8069/web/assets/454-e79ddd1/web.assets_common.min.js:1443:96
    render@http://192.168.1.30:8069/web/assets/454-e79ddd1/web.assets_common.min.js:1442:6
    initiateRender@http://192.168.1.30:8069/web/assets/454-e79ddd1/web.assets_common.min.js:1520:47
    ```

**Comment by Foster2** [comment]
You can try to regenerate the assets.

1. Enable the Developer Mode
2. Regenerate Assets Bundles

**Comment by jacobmason** [comment]
Unfortunately I can't access any settings menus due to this error.

**Comment by Foster2** [comment]
> Unfortunately I can't access any settings menus due to this error.

You can append the url with &debug=assets to enable developer mode.

**Comment by nnmalex** [comment]
I have the same issue, updating base module doesn't help and I can't access settings to regenerate bundles because of the issue.

**Comment by nnmalex** [comment]
What I did as a temporary fix was building my own image from the Dockerfile in this repo using the .deb file version in this issue: https://github.com/odoo/odoo/issues/117742

**Comment by yal-firyal** [comment]
Hello everyone.
I need help. I have the same problem. I can't get into the settings menu because then it gives me the same error.

UncaughtPromiseError > OwlError
Uncaught Promise > Invalid prop suffix
OwlError: Invalid prop suffix
    OwlError@http://localhost:10016/web/assets/249-9fa5c22/web.assets_common.min.js:1133:1
    formatProp@http://localhost:10016/web/assets/249-9fa5c22/web.assets_common.min.js:1789:12
    formatPropObject/<@http://localhost:10016/web/assets/249-9fa5c22/web.assets_common.min.js:1791:68
    formatPropObject@http://localhost:10016/web/assets/249-9fa5c22/web.assets_common.min.js:1791:50
    compileComponent@http://localhost:10016/web/assets/249-9fa5c22/web.assets_common.min.js:1794:113
    compileAST@http://localhost:10016/web/assets/249-9fa5c22/web.assets_common.min.js:1686:558
    compileTDomNode@http://localhost:10016/web/assets/249-9fa5c22/web.assets_common.min.js:1722:368
    compileAST@http://localhost:10016/web/assets/249-9fa5c22/web.assets_common.min.js:1686:140
    compileInNewTarget@http://localhost:10016/web/assets/249-9fa5c22/web.assets_common.min.js:1670:188
    compileComponent@http://localhost:10016/web/assets/249-9fa5c22/web.assets_common.min.js:1795:133
    compileAST@http://localhost:10016/web/assets/249-9fa5c22/web.assets_common.min.js:1686:558
    compileMulti@http://localhost:10016/web/assets/249-9fa5c22/web.assets_common.min.js:1764:239
    compileAST@http://localhost:10016/web/assets/249-9fa5c22/web.assets_common.min.js:1686:388
    compileInNewTarget@http://localhost:10016/web/assets/249-9fa5c22/web.assets_common.min.js:1670:188
    compileComponent@http://localhost:10016/web/assets/249-9fa5c22/web.assets_common.min.js:1795:133
    compileAST@http://localhost:10016/web/assets/249-9fa5c22/web.assets_common.min.js:1686:558
    compileTDomNode@http://localhost:10016/web/assets/249-9fa5c22/web.assets_common.min.js:1722:368
    compileAST@http://localhost:10016/web/assets/249-9fa5c22/web.assets_common.min.js:1686:140
    compileMulti@http://localhost:10016/web/assets/249-9fa5c22/web.assets_common.min.js:1764:239
    compileAST@http://localhost:10016/web/assets/249-9fa5c22/web.assets_common.min.js:1686:388
    compileInNewTarget@http://localhost:10016/web/assets/249-9fa5c22/web.assets_common.min.js:1670:188
    compileComponent@http://localhost:10016/web/assets/249-9fa5c22/web.assets_common.min.js:1795:133
    compileAST@http://localhost:10016/web/assets/249-9fa5c22/web.assets_common.min.js:1686:558
    compileMulti@http://localhost:10016/web/assets/249-9fa5c22/web.assets_common.min.js:1764:239
    compileAST@http://localhost:10016/web/assets/249-9fa5c22/web.assets_common.min.js:1686:388
    compileInNewTarget@http://localhost:10016/web/assets/249-9fa5c22/web.assets_common.min.js:1670:188
    compileComponent@http://localhost:10016/web/assets/249-9fa5c22/web.assets_common.min.js:1795:133
    compileAST@http://localhost:10016/web/assets/249-9fa5c22/web.assets_common.min.js:1686:558
    compileTDomNode@http://localhost:10016/web/assets/249-9fa5c22/web.assets_common.min.js:1722:368
    compileAST@http://localhost:10016/web/assets/249-9fa5c22/web.assets_common.min.js:1686:140
    compileTDomNode@http://localhost:10016/web/assets/249-9fa5c22/web.assets_common.min.js:1722:368
    compileAST@http://localhost:10016/web/assets/249-9fa5c22/web.assets_common.min.js:1686:140
    generateCode@http://localhost:10016/web/assets/249-9fa5c22/web.assets_common.min.js:1662:113
    compile@http://localhost:10016/web/assets/249-9fa5c22/web.assets_common.min.js:1932:348
    _compileTemplate@http://localhost:10016/web/assets/249-9fa5c22/web.assets_common.min.js:1983:280
    _compileTemplate@http://localhost:10016/web/assets/249-9fa5c22/web.assets_common.min.js:1993:83
    getTemplate@http://localhost:10016/web/assets/249-9fa5c22/web.assets_common.min.js:1596:118
    callTemplate@http://localhost:10016/web/assets/249-9fa5c22/web.assets_common.min.js:1599:68
    template@http://localhost:10016/web/assets/249-9fa5c22/web.assets_common.min.js line 1932 > Function:9:12
    _render@http://localhost:10016/web/assets/249-9fa5c22/web.assets_common.min.js:1371:96
    render@http://localhost:10016/web/assets/249-9fa5c22/web.assets_common.min.js:1370:6
    initiateRender@http://localhost:10016/web/assets/249-9fa5c22/web.assets_common.min.js:1449:47

**Comment by jwaes** [comment]
> I am facing the same problem, I've the latest docker image, and I'm using the docker-compose.yml

add this line for the odoo service in your yaml file:

`    entrypoint: "/entrypoint.sh -u all"`
