### ISSUE TITLE
Odoo studio installation

### ISSUE THREAD

**Issue by Emad-teleyemen** [odoo/docker#450]
When I try to install studio an internal error shows 
When i looked up the logs it shows the following error

Traceback (most recent call last):
2023-05-08T06:30:32.991082827Z   File "/usr/lib/python3/dist-packages/odoo/tools/[cache.py",](https://cache.py/) line 85, in lookup
2023-05-08T06:30:32.991084790Z     r = d[key]
2023-05-08T06:30:32.991086482Z   File "", line 2, in __getitem__
2023-05-08T06:30:32.991088478Z   File "/usr/lib/python3/dist-packages/odoo/tools/[func.py",](https://func.py/) line 87, in locked
2023-05-08T06:30:32.991090187Z     return func(inst, *args, **kwargs)
2023-05-08T06:30:32.991091677Z   File "/usr/lib/python3/dist-packages/odoo/tools/[lru.py",](https://lru.py/) line 34, in __getitem__
2023-05-08T06:30:32.991093416Z     a = self.d[obj]
2023-05-08T06:30:32.991094921Z KeyError: ('ir.qweb', , 'web.assets_backend', False, True, '', False, False, False, False, ('en_US', None, None, None, None, None, None))
2023-05-08T06:30:32.991096730Z 
2023-05-08T06:30:32.991098218Z During handling of the above exception, another exception occurred:
2023-05-08T06:30:32.991099764Z 
2023-05-08T06:30:32.991101152Z Traceback (most recent call last):
2023-05-08T06:30:32.991102647Z   File "<190>", line 323, in template_190
2023-05-08T06:30:32.991104253Z   File "<190>", line 305, in template_190_content
2023-05-08T06:30:32.991105854Z   File "<190>", line 274, in template_190_t_call_0
2023-05-08T06:30:32.991107407Z   File "<190>", line 191, in template_190_t_set_2
2023-05-08T06:30:32.991121322Z   File "/usr/lib/python3/dist-packages/odoo/addons/base/models/[ir_qweb.py",](https://ir_qweb.py/) line 2415, in _get_asset_nodes
2023-05-08T06:30:32.991123173Z     return self._generate_asset_nodes_cache(bundle, css, js, debug, async_load, defer_load, lazy_load, media)
2023-05-08T06:30:32.991124861Z   File "", line 2, in _generate_asset_nodes_cache
2023-05-08T06:30:32.991126534Z   File "/usr/lib/python3/dist-packages/odoo/tools/[cache.py",](https://cache.py/) line 90, in lookup
2023-05-08T06:30:32.991128384Z     value = d[key] = self.method(*args, **kwargs)
2023-05-08T06:30:32.991130093Z   File "/usr/lib/python3/dist-packages/odoo/addons/base/models/[ir_qweb.py",](https://ir_qweb.py/) line 2470, in _generate_asset_nodes_cache
2023-05-08T06:30:32.991139988Z     return self._generate_asset_nodes(bundle, css, js, debug, async_load, defer_load, lazy_load, media)
2023-05-08T06:30:32.991141765Z   File "/usr/lib/python3/dist-packages/odoo/addons/base/models/[ir_qweb.py",](https://ir_qweb.py/) line 2544, in _generate_asset_nodes
2023-05-08T06:30:32.991143488Z     return remains + asset.to_node(css=css, js=js, debug=debug, async_load=async_load, defer_load=defer_load, lazy_load=lazy_load)
2023-05-08T06:30:32.991145139Z   File "/usr/lib/python3/dist-packages/odoo/addons/base/models/[assetsbundle.py",](https://assetsbundle.py/) line 181, in to_node
2023-05-08T06:30:32.991146760Z     js_attachment = self.js(is_minified=not is_debug_assets)
2023-05-08T06:30:32.991148782Z   File "/usr/lib/python3/dist-packages/odoo/addons/base/models/[assetsbundle.py",](https://assetsbundle.py/) line 394, in js
2023-05-08T06:30:32.991150396Z     content.append(self.xml(show_inherit_info=not is_minified))
2023-05-08T06:30:32.991151926Z   File "/usr/lib/python3/dist-packages/odoo/addons/base/models/[assetsbundle.py",](https://assetsbundle.py/) line 556, in xml
2023-05-08T06:30:32.991153563Z     inherited_template = apply_inheritance_specs(parent_tree, xpaths)
2023-05-08T06:30:32.991155083Z   File "/usr/lib/python3/dist-packages/odoo/tools/[template_inheritance.py",](https://template_inheritance.py/) line 265, in apply_inheritance_specs
2023-05-08T06:30:32.991156747Z     raise ValueError(
2023-05-08T06:30:32.991158225Z ValueError: Element '' cannot be located in parent view
2023-05-08T06:30:32.991159956Z 
2023-05-08T06:30:32.991161406Z The above exception was the direct cause of the following exception:
2023-05-08T06:30:32.991162926Z 
2023-05-08T06:30:32.991164560Z Traceback (most recent call last):
2023-05-08T06:30:32.991166079Z   File "/usr/lib/python3/dist-packages/odoo/[http.py",](https://http.py/) line 1987, in __call__
2023-05-08T06:30:32.991167702Z     response = request._serve_db()
2023-05-08T06:30:32.991169152Z   File "/usr/lib/python3/dist-packages/odoo/[http.py",](https://http.py/) line 1583, in _serve_db
2023-05-08T06:30:32.991170796Z     return service_model.retrying(self._serve_ir_http, self.env)
2023-05-08T06:30:32.991172328Z   File "/usr/lib/python3/dist-packages/odoo/service/[model.py",](https://model.py/) line 134, in retrying
2023-05-08T06:30:32.991173920Z     result = func()
2023-05-08T06:30:32.991175394Z   File "/usr/lib/python3/dist-packages/odoo/[http.py",](https://http.py/) line 1610, in _serve_ir_http
2023-05-08T06:30:32.991177053Z     response = [self.dispatcher.dispatch(rule.endpoint,](https://self.dispatcher.dispatch(rule.endpoint,/) args)
2023-05-08T06:30:32.991178623Z   File "/usr/lib/python3/dist-packages/odoo/[http.py",](https://http.py/) line 1723, in dispatch
2023-05-08T06:30:32.991180185Z     return [self.request.registry['ir.http']._dispatch(endpoint)](https://self.request.registry%5B'ir.http'%5D._dispatch(endpoint))
2023-05-08T06:30:32.991181677Z   File "/usr/lib/python3/dist-packages/odoo/addons/base/models/[ir_http.py",](https://ir_http.py/) line 156, in _dispatch
2023-05-08T06:30:32.991183298Z     result.flatten()
2023-05-08T06:30:32.991184816Z   File "/usr/lib/python3/dist-packages/odoo/[http.py",](https://http.py/) line 1098, in flatten
2023-05-08T06:30:32.991188518Z     [self.response.append(self.render())](https://self.response.append(self.render())/)
2023-05-08T06:30:32.991190026Z   File "/usr/lib/python3/dist-packages/odoo/[http.py",](https://http.py/) line 1090, in render
2023-05-08T06:30:32.991191581Z     return request.env["[ir.ui.view"]._render_template(self.template,](https://ir.ui.view/) self.qcontext)
2023-05-08T06:30:32.991193245Z   File "/usr/lib/python3/dist-packages/odoo/addons/base/models/[ir_ui_view.py",](https://ir_ui_view.py/) line 2128, in _render_template
2023-05-08T06:30:32.991194848Z     return self.env['ir.qweb']._render(template, values)
2023-05-08T06:30:32.991196354Z   File "/usr/lib/python3/dist-packages/odoo/tools/[profiler.py",](https://profiler.py/) line 292, in _tracked_method_render
2023-05-08T06:30:32.991197928Z     return method_render(self, template, values, **options)
2023-05-08T06:30:32.991199749Z   File "/usr/lib/python3/dist-packages/odoo/addons/base/models/[ir_qweb.py",](https://ir_qweb.py/) line 580, in _render
2023-05-08T06:30:32.991201350Z     result = ''.join(rendering)
2023-05-08T06:30:32.991202828Z   File "<190>", line 329, in template_190
2023-05-08T06:30:32.991204369Z [odoo.addons.base.models.ir_qweb.QWebException:](https://odoo.addons.base.models.ir_qweb.qwebexception/) Error while render the template
2023-05-08T06:30:32.991205973Z ValueError: Element '' cannot be located in parent view
2023-05-08T06:30:32.991213431Z Template: web.webclient_bootstrap
2023-05-08T06:30:32.991214982Z Path: /t/t/t[1]/t[4]
2023-05-08T06:30:32.991216523Z Node: 

I created a new clean database and the same problem kept happening.
I checked if there is any apps that were installed automatically but there was none.

**Comment by lathama** [comment]
@Emad-teleyemen can you confirm this with Odoo 17. I noticed https://github.com/odoo/odoo/issues/126928 which was fixed with an update. Please provide version of Odoo to help narrow down the issue.
