### ISSUE TITLE
docker map directory permission error

### ISSUE THREAD

**Issue by forzenheart** [odoo/docker#481]
when i run with:
sudo docker run -v /home/ubuntu/odoo/data/:/var/lib/odoo
get error like this:  

  path = odoo.tools.config.session_dir
  File "/usr/lib/python3/dist-packages/odoo/tools/config.py", line 723, in session_dir
    os.makedirs(d, 0o700)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/var/lib/odoo/sessions' - - -

**Comment by pharpe** [comment]
I'm getting simular errors

`2024-01-10 20:15:02,529 1 INFO ? werkzeug: 192.168.1.1 - - [10/Jan/2024 20:15:02] "GET /favicon.ico HTTP/1.1" 500 - 0 0.000 0.001
2024-01-10 20:15:02,531 1 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 319, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 308, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 2151, in __call__
    request._post_init()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1309, in _post_init
    self.session, self.db = self._get_session_and_dbname()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1326, in _get_session_and_dbname
    session = root.session_store.new()
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 28, in __get__
    value = self.fget(obj)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 2074, in session_store
    path = odoo.tools.config.session_dir
  File "/usr/lib/python3/dist-packages/odoo/tools/config.py", line 724, in session_dir
    os.makedirs(d, 0o700)
  File "/usr/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/var/lib/odoo/.local' - - -`

**Comment by SmartPhoneLover** [comment]
Did you solve it?

**Comment by cap-jmk** [comment]
Same problem in podman 4.3.1
