### ISSUE TITLE
Oddo don't work on Unraid

### ISSUE THREAD

**Issue by PrzemekSkw** [odoo/docker#489]
I install oddo17 container and set postgresql15 db name and password.
I try to enter webui on local address but get:
```Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```
Logs shows me:
```
2024-01-11 16:47:18,865 1 INFO ? werkzeug: 192.168.0.215 - - [11/Jan/2024 16:47:18] "GET /favicon.ico HTTP/1.1" 500 - 0 0.000 0.001
2024-01-11 16:47:18,867 1 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 319, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python3/dist-packages/werkzeug/serving.py", line 308, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 2151, in __call__
    request._post_init()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1309, in _post_init
    self.session, self.db = self._get_session_and_dbname()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 1326, in _get_session_and_dbname
    session = root.session_store.new()
  File "/usr/lib/python3/dist-packages/odoo/tools/func.py", line 28, in __get__
    value = self.fget(obj)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 2074, in session_store
    path = odoo.tools.config.session_dir
  File "/usr/lib/python3/dist-packages/odoo/tools/config.py", line 724, in session_dir
    os.makedirs(d, 0o700)
  File "/usr/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.10/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/usr/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/var/lib/odoo/.local' - - -
2024-01-11 16:48:55,974 1 INFO ? odoo.service.server: Initiating shutdown 
2024-01-11 16:48:55,974 1 INFO ? odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2024-01-11 16:48:56,464 1 INFO ? odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 2 connections  
grep: /etc/odoo/odoo.conf: No such file or directory
grep: /etc/odoo/odoo.conf: No such file or directory
grep: /etc/odoo/odoo.conf: No such file or directory
grep: /etc/odoo/odoo.conf: No such file or directory
2024-01-11 16:49:39,087 1 INFO ? odoo: Odoo version 17.0-20240104 
2024-01-11 16:49:39,087 1 INFO ? odoo: addons paths: ['/usr/lib/python3/dist-packages/odoo/addons'] 
2024-01-11 16:49:39,087 1 INFO ? odoo: database: odoo@192.168.0.208:5433 
2024-01-11 16:49:39,129 1 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at /usr/local/bin/wkhtmltopdf 
2024-01-11 16:49:39,205 1 INFO ? odoo.service.server: HTTP service (werkzeug) running on 03b2eb740fdd:8069 
```
Regards

**Comment by ProLoader42** [comment]
I have the same issue.

**Comment by amh-mw** [comment]
`/var/lib/odoo/.local` jumps out at me as unfamiliar. What do your volume mounts look like?

**Comment by PrzemekSkw** [comment]
Looks like that:
![image](https://github.com/odoo/docker/assets/25219988/8e85d0a3-bf44-4258-8511-ba610597a792)

**Comment by PrzemekSkw** [comment]
There's also in logs:
`grep: /etc/odoo/odoo.conf: No such file or directory`
How to create config?

**Comment by amh-mw** [comment]
This is definitely smelling like a file permissions issue. You should make sure that the system user that is running your odoo process has read access to your extra-addons and config folders and write access to your data folder.

**Comment by PrzemekSkw** [comment]
Every docker app folder have owner - nobody.
Odoo has root as owner. 
I change for nobody but still the same errors.

**Comment by ProLoader42** [comment]
@PrzemekSkw there is a new template from Eurotimmy in the CA. Install the container with the new template and make odoo:101 the new owner of the mounted paths within the Docker.

`chown -R odoo:101 /etc/odoo
chown -R odoo:101 /mnt/extra-addons`

This fixed it for me.

**Comment by PrzemekSkw** [comment]
> @PrzemekSkw there is a new template from Eurotimmy in the CA. Install the container with the new template and make odoo:101 the new owner of the mounted paths within the Docker.
> 
> `chown -R odoo:101 /etc/odoo` `chown -R odoo:101 /mnt/extra-addons`
> 
> This fixed it for me.

Hi, I install it now with readme.md guide and it work now.
Regards.
