### ISSUE TITLE
Odoo Server Errros by generating a new offer

### ISSUE THREAD

**Issue by micky7** [odoo/docker#50]
Hi,

i set docker image an created a database with the demo data's. When i generate a new offer and add product, i will get this error messages. What am i doing wrong.

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 605, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 642, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 316, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 309, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 893, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/http.py", line 471, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 892, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/addons/web/controllers/main.py", line 884, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 238, in wrapper
    return old_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 369, in old_api
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 5985, in onchange
    record = self.new(values)
  File "/usr/lib/python2.7/dist-packages/openerp/api.py", line 236, in wrapper
    return new_api(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 5555, in new
    record._cache.update(record._convert_to_cache(values, update=True))
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 5450, in _convert_to_cache
    for name, value in values.iteritems()
  File "/usr/lib/python2.7/dist-packages/openerp/models.py", line 5451, in <dictcomp>
    if name in fields
  File "/usr/lib/python2.7/dist-packages/openerp/fields.py", line 1743, in convert_to_cache
    ids = OrderedSet(command[2])
  File "/usr/lib/python2.7/dist-packages/openerp/tools/misc.py", line 1106, in __init__
    super(OrderedSet, self).__init__([(x, None) for x in seq])
  File "/usr/lib/python2.7/collections.py", line 52, in __init__
    self.__update(*args, **kwds)
  File "/usr/lib/python2.7/_abcoll.py", line 567, in update
    self[key] = value
  File "/usr/lib/python2.7/collections.py", line 58, in __setitem__
    if key not in self:
TypeError: unhashable type: 'list'

Best regards

**Comment by sle-odoo** [comment]
This look like a bug in the upstream repository and it was fixed in the meantime.
Thank you for reporting it anyway.

Regards
